import { buildOrientation } from "../../content/orientation/copy.ts";
import { parseGame } from "../../src/game-engine/schema.ts";

const sample = {
  id: "example-custom-game",
  status: "prototype",
  title: "Example custom game",
  tier: 1,
  order: 99,
  summary: "A minimal game used by the documentation and the content test. It is not registered in the course.",
  purpose: "Show the smallest definition the schema accepts.",
  whyItMatters: "Educators can add a round without editing React when an existing interaction type is enough.",
  learningObjectives: ["Identify the option marked best in a two-choice round."],
  concepts: ["Content schema"],
  bloomLevels: ["understand"],
  prerequisites: [],
  estimatedMinutes: 5,
  difficulty: "foundational",
  masteryThreshold: 70,
  misconception: "A new challenge does not require a new component when the interaction type already exists.",
  reflectionPrompt: "What would you change in the hint text?",
  workedExample: { title: "Read the card", steps: ["Compare the two descriptions.", "Lock the round."] },
  furtherReadingIds: ["vaswani2017"],
  implementation: {
    type: "deterministic-simulation",
    label: "Example only",
    whatIsReal: "The score for the selected card.",
    whatIsSimulated: "Nothing is executed beyond the card label.",
  },
  orientation: buildOrientation({
    tagline: "A minimal example of the orientation every game must include.",
    overview: "This example shows the smallest orientation the schema accepts. It is not part of the course.",
    whyItMatters: "Educators can see the required sections before they copy the file.",
    learningObjectives: [
      "Identify the option marked best in a two-choice round.",
      "Name the hint penalty before playing.",
      "Distinguish completion from mastery on the result screen.",
    ],
    whatYouWillDo: "You compare two cards and lock the round.",
    howToPlay: ["Read the task.", "Compare the cards.", "Select one.", "Lock the round.", "Read the feedback."],
    howItWorks: "The score is the label on the card. Nothing else is executed. This is an example, not a simulation of a model.",
    earns: "The card marked best scores 10. The other scores 0.",
    roundCount: 1,
    efficiencyMatters: "Efficiency is not part of this example.",
    multipleAcceptableAnswers: "No. One card is marked best.",
    mastery: "You can explain which card matched the task.",
    rounds: [{ label: "Round 1", difficulty: "Introductory", focus: "Read the card" }],
    recommendedNext: "Return to the course list.",
    implementationNote: "Simulation disclosure: this example only scores the selected card. It is not a live system.",
    estimatedTime: "About 5 minutes",
    beforeYouStart: ["Read both cards.", "The schema validates this file when tests run."],
    selfCheck: ["Can I say which card fit?", "Can I say this example is not a course game?"],
    reflectionPrompts: ["What would you change in the hint text?", "What would you add before a learner starts?"],
    roundGuides: [
      {
        difficulty: "Introductory",
        goal: "Select the card whose description matches the task.",
        tradeoff: "Skipping validation ships a file the schema will reject.",
        takeaway: "Validate the definition before shipping it.",
        realSystem: "A content error should fail at load time, not in front of a learner.",
      },
    ],
  }),
  rounds: [
    {
      id: "only-round",
      title: "One choice",
      concept: "Content schema",
      learnerTask: "Select the card marked as the better fit.",
      expectedReasoning: "The best card is the one whose description matches the task.",
      scenario: "This round exists so a test can parse educator content outside the 13 games.",
      hints: ["Read both cards.", "The task asks for the better fit.", "The card that names the schema is the best fit in this example."],
      scoringRule: "Best scores 10. Poor scores 0. Each hint subtracts 1.",
      explanation: "The example is not part of the learner course.",
      feedbackCorrect: "That card is the one the example marks best.",
      feedbackIncorrect: "The other card is the one the example marks best.",
      interaction: {
        type: "choice",
        prompt: "Which card fits?",
        options: [
          {
            id: "schema",
            label: "Use the schema",
            description: "Validate the definition before shipping it.",
            metrics: [{ label: "Fits", value: "Yes", tone: "good" }],
            quality: "best",
          },
          {
            id: "skip",
            label: "Skip validation",
            description: "Ship the file and hope the UI notices.",
            metrics: [{ label: "Fits", value: "No", tone: "poor" }],
            quality: "poor",
          },
        ],
      },
    },
  ],
};

export const customGame = parseGame(sample, "examples/custom-game/sample.ts");
