export interface ReferenceEntry {
  id: string;
  authors: string;
  year: number;
  title: string;
  venue: string;
  url: string;
}

export const references: ReferenceEntry[] = [
  {
    id: "vaswani2017",
    authors: "Ashish Vaswani, Noam Shazeer, Niki Parmar, Jakob Uszkoreit, Llion Jones, Aidan N. Gomez, Łukasz Kaiser, and Illia Polosukhin",
    year: 2017,
    title: "Attention Is All You Need",
    venue: "Advances in Neural Information Processing Systems",
    url: "https://arxiv.org/abs/1706.03762",
  },
  {
    id: "sennrich2016",
    authors: "Rico Sennrich, Barry Haddow, and Alexandra Birch",
    year: 2016,
    title: "Neural Machine Translation of Rare Words with Subword Units",
    venue: "Proceedings of the 54th Annual Meeting of the Association for Computational Linguistics",
    url: "https://aclanthology.org/P16-1162/",
  },
  {
    id: "schuster2012",
    authors: "Mike Schuster and Kaisuke Nakajima",
    year: 2012,
    title: "Japanese and Korean Voice Search",
    venue: "IEEE International Conference on Acoustics, Speech and Signal Processing",
    url: "https://doi.org/10.1109/ICASSP.2012.6289079",
  },
  {
    id: "kudo2018sentencepiece",
    authors: "Taku Kudo and John Richardson",
    year: 2018,
    title: "SentencePiece: A simple and language independent subword tokenizer and detokenizer for neural text processing",
    venue: "Proceedings of the 2018 Conference on Empirical Methods in Natural Language Processing: System Demonstrations",
    url: "https://arxiv.org/abs/1808.06226",
  },
  {
    id: "kudo2018unigram",
    authors: "Taku Kudo",
    year: 2018,
    title: "Subword Regularization: Improving Neural Network Translation Models with Multiple Subword Candidates",
    venue: "Proceedings of the 56th Annual Meeting of the Association for Computational Linguistics",
    url: "https://arxiv.org/abs/1804.10959",
  },
  {
    id: "hu2021lora",
    authors: "Edward J. Hu, Yelong Shen, Phillip Wallis, Zeyuan Allen-Zhu, Yuanzhi Li, Shean Wang, Lu Wang, and Weizhu Chen",
    year: 2021,
    title: "LoRA: Low-Rank Adaptation of Large Language Models",
    venue: "arXiv:2106.09685",
    url: "https://arxiv.org/abs/2106.09685",
  },
  {
    id: "lewis2020rag",
    authors: "Patrick Lewis, Ethan Perez, Aleksandra Piktus, Fabio Petroni, Vladimir Karpukhin, Naman Goyal, Heinrich Küttler, Mike Lewis, Wen-tau Yih, Tim Rocktäschel, Sebastian Riedel, and Douwe Kiela",
    year: 2020,
    title: "Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks",
    venue: "Advances in Neural Information Processing Systems",
    url: "https://arxiv.org/abs/2005.11401",
  },
  {
    id: "karpukhin2020dpr",
    authors: "Vladimir Karpukhin, Barlas Oğuz, Sewon Min, Patrick Lewis, Ledell Wu, Sergey Edunov, Danqi Chen, and Wen-tau Yih",
    year: 2020,
    title: "Dense Passage Retrieval for Open-Domain Question Answering",
    venue: "Proceedings of the 2020 Conference on Empirical Methods in Natural Language Processing",
    url: "https://arxiv.org/abs/2004.04906",
  },
  {
    id: "reimers2019sbert",
    authors: "Nils Reimers and Iryna Gurevych",
    year: 2019,
    title: "Sentence-BERT: Sentence Embeddings using Siamese BERT-Networks",
    venue: "Proceedings of the 2019 Conference on Empirical Methods in Natural Language Processing",
    url: "https://arxiv.org/abs/1908.10084",
  },
  {
    id: "ouyang2022instructgpt",
    authors: "Long Ouyang, Jeffrey Wu, Xu Jiang, Diogo Almeida, Carroll L. Wainwright, Pamela Mishkin, Chong Zhang, Sandhini Agarwal, Katarina Slama, Alex Ray, John Schulman, Jacob Hilton, Fraser Kelton, Luke Miller, Maddie Simens, Amanda Askell, Peter Welinder, Paul Christiano, Jan Leike, and Ryan Lowe",
    year: 2022,
    title: "Training language models to follow instructions with human feedback",
    venue: "arXiv:2203.02155",
    url: "https://arxiv.org/abs/2203.02155",
  },
  {
    id: "christiano2017preferences",
    authors: "Paul F. Christiano, Jan Leike, Tom B. Brown, Miljan Martic, Shane Legg, and Dario Amodei",
    year: 2017,
    title: "Deep Reinforcement Learning from Human Preferences",
    venue: "Advances in Neural Information Processing Systems",
    url: "https://arxiv.org/abs/1706.03741",
  },
  {
    id: "wei2022cot",
    authors: "Jason Wei, Xuezhi Wang, Dale Schuurmans, Maarten Bosma, Brian Ichter, Fei Xia, Ed Chi, Quoc Le, and Denny Zhou",
    year: 2022,
    title: "Chain-of-Thought Prompting Elicits Reasoning in Large Language Models",
    venue: "arXiv:2201.11903",
    url: "https://arxiv.org/abs/2201.11903",
  },
  {
    id: "wang2023selfconsistency",
    authors: "Xuezhi Wang, Jason Wei, Dale Schuurmans, Quoc Le, Ed Chi, Sharan Narang, Aakanksha Chowdhery, and Denny Zhou",
    year: 2023,
    title: "Self-Consistency Improves Chain of Thought Reasoning in Language Models",
    venue: "International Conference on Learning Representations",
    url: "https://arxiv.org/abs/2203.11171",
  },
  {
    id: "yao2023tot",
    authors: "Shunyu Yao, Dian Yu, Jeffrey Zhao, Izhak Shafran, Thomas L. Griffiths, Yuan Cao, and Karthik Narasimhan",
    year: 2023,
    title: "Tree of Thoughts: Deliberate Problem Solving with Large Language Models",
    venue: "arXiv:2305.10601",
    url: "https://arxiv.org/abs/2305.10601",
  },
  {
    id: "brown2020gpt3",
    authors: "Tom B. Brown, Benjamin Mann, Nick Ryder, Melanie Subbiah, Jared Kaplan, Prafulla Dhariwal, Arvind Neelakantan, Pranav Shyam, Girish Sastry, Amanda Askell, and others",
    year: 2020,
    title: "Language Models are Few-Shot Learners",
    venue: "Advances in Neural Information Processing Systems",
    url: "https://arxiv.org/abs/2005.14165",
  },
  {
    id: "bommasani2022foundation",
    authors: "Rishi Bommasani and colleagues",
    year: 2022,
    title: "On the Opportunities and Risks of Foundation Models",
    venue: "arXiv:2108.07258",
    url: "https://arxiv.org/abs/2108.07258",
  },
  {
    id: "huyen2022dmls",
    authors: "Chip Huyen",
    year: 2022,
    title: "Designing Machine Learning Systems",
    venue: "O'Reilly Media",
    url: "https://www.oreilly.com/library/view/designing-machine-learning/9781098107956/",
  },
  {
    id: "zamfirescu2023prompt",
    authors: "J.D. Zamfirescu-Pereira, Richmond Y. Wong, Bjoern Hartmann, and Qian Yang",
    year: 2023,
    title: "Why Johnny Can't Prompt: How Non-AI Experts Try (and Fail) to Design LLM Prompts",
    venue: "CHI Conference on Human Factors in Computing Systems",
    url: "https://doi.org/10.1145/3544548.3581388",
  },
  {
    id: "black1998feedback",
    authors: "Paul Black and Dylan Wiliam",
    year: 1998,
    title: "Assessment and Classroom Learning",
    venue: "Assessment in Education: Principles, Policy & Practice, 5(1)",
    url: "https://doi.org/10.1080/0969595980050102",
  },
  {
    id: "vygotsky1978",
    authors: "L. S. Vygotsky",
    year: 1978,
    title: "Mind in Society: The Development of Higher Psychological Processes",
    venue: "Harvard University Press",
    url: "https://www.hup.harvard.edu/books/9780674576292",
  },
  {
    id: "sweller2011clt",
    authors: "John Sweller",
    year: 2011,
    title: "Cognitive Load Theory",
    venue: "Psychology of Learning and Motivation, Vol. 55",
    url: "https://doi.org/10.1016/B978-0-12-387691-1.00002-8",
  },
  {
    id: "csikszentmihalyi1990flow",
    authors: "Mihaly Csikszentmihalyi",
    year: 1990,
    title: "Flow: The Psychology of Optimal Experience",
    venue: "Harper & Row",
    url: "https://search.worldcat.org/search?q=Flow%3A+The+Psychology+of+Optimal+Experience+Csikszentmihalyi",
  },
  {
    id: "bloom1968mastery",
    authors: "Benjamin S. Bloom",
    year: 1968,
    title: "Learning for Mastery",
    venue: "Evaluation Comment, 1(2)",
    url: "https://eric.ed.gov/?id=ED053419",
  },
  {
    id: "anderson2001bloom",
    authors: "Lorin W. Anderson, David R. Krathwohl, and colleagues",
    year: 2001,
    title: "A Taxonomy for Learning, Teaching, and Assessing: A Revision of Bloom's Taxonomy of Educational Objectives",
    venue: "Longman",
    url: "https://search.worldcat.org/search?q=A+Taxonomy+for+Learning+Teaching+and+Assessing+Anderson+Krathwohl",
  },
  {
    id: "deci2008sdt",
    authors: "Edward L. Deci and Richard M. Ryan",
    year: 2008,
    title: "Self-Determination Theory: A Macrotheory of Human Motivation, Development, and Health",
    venue: "Canadian Psychology, 49(3)",
    url: "https://doi.org/10.1037/a0012801",
  },
  {
    id: "brown1989situated",
    authors: "John Seely Brown, Allan Collins, and Paul Duguid",
    year: 1989,
    title: "Situated Cognition and the Culture of Learning",
    venue: "Educational Researcher, 18(1)",
    url: "https://doi.org/10.3102/0013189X018001032",
  },
  {
    id: "hamari2014gamification",
    authors: "Juho Hamari, Jonna Koivisto, and Harri Sarsa",
    year: 2014,
    title: "Does Gamification Work? — A Literature Review of Empirical Studies on Gamification",
    venue: "47th Hawaii International Conference on System Sciences",
    url: "https://doi.org/10.1109/HICSS.2014.377",
  },
  {
    id: "piaget1954",
    authors: "Jean Piaget",
    year: 1954,
    title: "The Construction of Reality in the Child",
    venue: "Basic Books",
    url: "https://doi.org/10.1037/11168-000",
  },
];

export function referenceById(id: string): ReferenceEntry | undefined {
  return references.find((entry) => entry.id === id);
}
