import type { GameTeaching } from "../../src/game-engine/schema.ts";

export const gradientTeaching: GameTeaching = {
  atAGlance: {
    tierExplanation: "Cognitive Core. Adaptation is taught as a curve with constraints, not as a recipe.",
    recommendedLevel: "Intermediate. Students should be willing to read two lines on a chart.",
    timeExplanation: "About 25 minutes.",
    activityType: "Set learning rate, epochs, batch size, and full fine-tuning versus LoRA until an educational curve meets the targets.",
    masteryExplanation: "70% means the educational model met the targets. It does not mean a real network was trained, and it does not mean full fine-tuning is universally best for medical or legal work.",
    statusExplanation: "Playable Prototype. The curves come from a documented formula. No parameters are trained. The activity remains under refinement.",
  },
  whyThisGameExists: [
    "Fine-tuning advice arrives as recipes: a learning rate, a batch size, “use LoRA.” Students cannot see why a recipe fails when the only picture is a slogan.",
    "The interaction is a curve because the failure modes have shapes: divergence, a widening gap, a floor the method cannot beat, a forgetting penalty. A formula can show those shapes without renting a GPU.",
    "The engineering stake is real: adapting a model can help a task and can also overwrite earlier behavior or overfit a small set. The decision depends on evidence, not on a domain label.",
  ],
  bloomExplanation: "Understand → Apply → Analyze. Students recognize a shape, apply a control, and analyze whether the evidence is underfitting, overfitting, or forgetting.",
  misconceptions: [
    { statement: "A falling training loss is treated as success.", howTheGameAddressesIt: "Targets include validation loss, the gap, stability, and forgetting." },
    { statement: "Full fine-tuning is treated as always best for high-stakes domains.", howTheGameAddressesIt: "Some rounds require LoRA because of forgetting. Others require more capacity. The domain does not decide." },
  ],
  assigning: { required: "The idea that a model has adjustable parameters and a loss.", helpful: "A first exposure to train versus validation.", notRequired: "PyTorch, a GPU, or a dataset." },
  difficultyExplanation: "Intermediate: controls are few and the formula is educational. Students are not implementing backpropagation.",
  roundNotes: [
    { practicing: "A learning rate that diverges.", whyChosen: "Divergence is the clearest “stop” signal.", watchFor: "A curve that climbs.", whatMattered: "Stability before speed.", alternatives: "More epochs do not repair a learning rate the scenario marks as unstable." },
    { practicing: "The generalization gap.", whyChosen: "Training loss can improve while validation does not.", watchFor: "The gap, not the lowest training point.", whatMattered: "Overfitting is a widening difference.", alternatives: "Chasing training loss past the overfitting epoch fails the target." },
    { practicing: "Catastrophic forgetting.", whyChosen: "Full updates can erase earlier behavior in this model.", watchFor: "The forgetting region.", whatMattered: "Preserving a prior task can be a constraint.", alternatives: "A lower loss that enters the forgetting region fails when the round forbids it." },
    { practicing: "A capacity floor.", whyChosen: "LoRA is not always enough. In this formula its floor can sit above the target.", watchFor: "Whether the method can represent the required loss.", whatMattered: "Underfitting can be a capacity problem.", alternatives: "Staying with LoRA because it is fashionable fails when the floor is too high." },
    { practicing: "Batch size and the gap.", whyChosen: "Batch size changes noise and the picture, not the goal.", watchFor: "The gap limit.", whatMattered: "A smoother curve is not the objective.", alternatives: "A tiny batch or a huge batch can both miss the target for different reasons." },
  ],
  scoringNarrative: "Five rounds, 10 or 0, when every target is met: validation loss, gap, stability, forgetting, and method if required. Hints subtract 1, floor 0. No accuracy or dollar figure on the chart is a measured training run. Mastery is 70%.",
  transferExplanation: "Transfer is pointing at evidence of underfitting or overfitting and justifying a change, while labeling the chart as a simulation.",
  selfEvaluationQuestions: ["Can I separate training loss from validation loss?", "Can I recognize divergence?", "Can I say what LoRA is giving up?", "Can I avoid a universal claim about full fine-tuning?"],
  guide: {
    title: "Understanding adaptation",
    overview: "Pretraining builds general parameters. Fine-tuning continues training on a narrower set. Gradients are the update direction. The loss is what the update reduces. Learning rate scales the step. Batch size is how many examples contribute to one step. An epoch is a pass over the training set. A validation set is the check that was not used for the update. A test set, if you have one, is held out even from that check. Overfitting memorizes the training set. Underfitting has not fit the pattern. Catastrophic forgetting is loss of earlier behavior. This game plots an educational formula for those ideas. It does not train.",
    keyConcepts: [
      { term: "Full fine-tuning", explanation: "Every trained parameter may move. Capacity is high. So is the chance of rewriting earlier behavior and the compute, in a real run." },
      { term: "LoRA", explanation: "LoRA represents an update as a low-rank product. If W is a weight matrix, the adapted matrix is W' = W + ΔW, with ΔW approximated by B times A, where the inner rank is much smaller than the original dimensions. That is a capacity choice, not a moral one. Label any loss you see here as simulated." },
      { term: "Other parameter-efficient methods", explanation: "Adapters and prefix or prompt tuning also train a small added piece. They are not interchangeable. Choose by measurement." },
      { term: "Curves in this game", explanation: "Costs, losses, and any accuracy-like reading are educational simulations unless a real training log is attached. None is attached." },
    ],
    howItWorks: "The chart calls the formula in the loss-curve module. Learning rate above the scenario maximum diverges. LoRA has a higher floor. Full fine-tuning can enter a forgetting region. Nothing is optimized with real gradients.",
    workedExamples: [{ title: "Reading a gap", label: "Educational simulation", body: "Training loss 0.2 and validation loss 0.9 is not a win if the target gap is 0.2. The story is overfitting, even if the training line looks excellent." }],
    visualNote: "Training and validation are two labeled lines. Divergence is described in text as well as in the slope.",
    applications: "Domain adaptation, style adaptation, and continued pretraining all need a decision about what may change and how you will know it worked.",
    tradeoffs: "Full updates can fit more and forget more. Low-rank updates can be cheaper and can underfit. The right side depends on the target and the forgetting constraint, not on the industry name.",
    bestPractices: ["Hold out validation.", "Plot both losses.", "Decide in advance what earlier behavior must survive.", "Re-evaluate on the task, not on the training loss."],
    pitfalls: ["Recipe without a curve.", "Calling a simulated loss a benchmark.", "Assuming medical or legal work always wants a full update.", "Tuning on the test set."],
    checkYourUnderstanding: ["What is the difference between a floor and a gap?", "What does the rank in LoRA limit?", "Why is a domain label not a training method?"],
    whenToUse: "Use it before anyone rents a GPU, to name the failure mode.",
    whenNotToUse: "Do not report these curves as experimental results.",
    productionConsiderations: "Real adaptation needs data governance, evaluation, and a rollback. The formula here is a teaching model of the shapes, not a substitute for that run.",
  },
  educator: {
    whyTeach: "Students otherwise memorize hyperparameters. The curve gives them evidence language.",
    whatStudentsDo: "They move controls until the educational targets are met.",
    evidencePrompts: ["Which line was the evidence?", "Why did you change the learning rate rather than the epoch count?", "What is simulated?"],
    beforeClass: "Define train, validation, and loss with one sketch.",
    duringClass: "Ask students to name the failure before they move a slider.",
    afterClass: "Write W' = W + BA on the board and say what the rank refuses to represent.",
    assignment: "Given a described curve, recommend one change and the measurement that would confirm it.",
    extension: "Discuss what you would log in a real run that this formula cannot show.",
    relatedGames: "Reasoning Reactor leaves the weights alone and designs the procedure around generation.",
  },
  discussionQuestions: ["Why can a lower training loss be bad news?", "What does LoRA not update?", "Why is “always full fine-tune for medicine” an unsupported absolute?", "What would you need before you trusted a real curve?"],
  nextConnection: { headline: "From weights to procedures", body: "Gradient Playground changes parameters in a simulation. Reasoning Reactor asks how to structure generation when you are not training.", path: "Adaptation evidence → generation procedure → still not hidden thoughts" },
};

export const reasoningTeaching: GameTeaching = {
  atAGlance: {
    tierExplanation: "Cognitive Core. The procedure around a sample becomes the lesson.",
    recommendedLevel: "Intermediate.",
    timeExplanation: "About 25 minutes.",
    activityType: "Assemble a visible workflow and a temperature, using a precomputed sample table.",
    masteryExplanation: "70% means the workflows matched these cases. It is not a claim about whether models reason.",
    statusExplanation: "Playable Prototype. Samples are written for the exercise. No model is sampled at runtime.",
  },
  whyThisGameExists: [
    "Students are told either that models reason or that they do not. Both slogans skip the engineering choice: what procedure you put around a sample, and what you are willing to check.",
    "Generation proceeds by next-token prediction. The nature and limits of reasoning in large language models remain active research questions. Prompted intermediate steps can improve some multi-step tasks. Visible reasoning text is not a faithful view of hidden computation.",
    "The game is appropriate because the workflow is something a student can specify: decompose, verify, sample, vote, or search. It does not require private chain-of-thought.",
  ],
  bloomExplanation: "Apply → Analyze. Students assemble a procedure and analyze whether the task needed a check, a vote, or a branch.",
  misconceptions: [
    { statement: "“Chain-of-thought forces reasoning” overclaims a prompt.", howTheGameAddressesIt: "The copy treats intermediate text as a possible performance aid and not as a window into hidden computation." },
    { statement: "A higher temperature is treated as more intelligent.", howTheGameAddressesIt: "Temperature is tied to diversity or agreement in a sample table, not to understanding." },
  ],
  assigning: { required: "The idea that a model returns a sample, not a proof.", helpful: "Promptsmith.", notRequired: "A sampler implementation or a claim about machine consciousness." },
  difficultyExplanation: "Intermediate: the pieces are a checklist. Students are not deriving decoding algorithms.",
  roundNotes: [
    { practicing: "External verification.", whyChosen: "Arithmetic can be recomputed. Another sample often cannot.", watchFor: "A check outside the model.", whatMattered: "A calculator does not repeat the same slip.", alternatives: "More samples without a check can repeat the error. A demand for hidden thoughts is not a check." },
    { practicing: "Diversity.", whyChosen: "Brainstorming fails when every sample is a paraphrase.", watchFor: "Whether a winner is forced too early.", whatMattered: "Temperature and the instruction have to allow distinct options.", alternatives: "Collapsing to one title defeats the task." },
    { practicing: "Self-consistency.", whyChosen: "When you cannot check, agreement is a weaker but available signal.", watchFor: "A vote over final answers, not a story about inner thought.", whatMattered: "Several samples cost more and can reduce a one-draw accident.", alternatives: "Trusting the first sample ignores the other draws. The vote still does not prove truth." },
    { practicing: "Search with a checker.", whyChosen: "Some tasks have rules that can reject a candidate.", watchFor: "The checker, not the prose of the search.", whatMattered: "Illegal moves should die even if they sound plausible.", alternatives: "A single greedy step is cheaper and brittle. Beam search is not essential for every task, including code." },
    { practicing: "Refusing a hidden trace.", whyChosen: "The assignment draws a line the field often blurs.", watchFor: "Public formula and source versus a private dump.", whatMattered: "Reviewable work is the artifact.", alternatives: "Asking for hidden chain-of-thought does not add a verifier." },
  ],
  scoringNarrative: "Five rounds. Required steps, no harmful step, and the best temperature score 10. Right steps with an acceptable temperature score 6. Otherwise 0. Hints subtract 1. Samples are precomputed. Mastery is 70%.",
  transferExplanation: "Transfer is choosing a workflow for a new task and saying why a verifier, a vote, or a branch is worth its cost.",
  selfEvaluationQuestions: ["Can I separate a public workflow from hidden computation?", "Can I say when temperature should be low?", "Can I explain self-consistency as a vote?", "Can I name a task where search is unnecessary?"],
  guide: {
    title: "Understanding generation procedures",
    overview: "A model proposes tokens. Decoding decides how the next token is chosen. Greedy decoding takes the most likely token each time. Temperature rescales probabilities: lower usually concentrates them, higher flattens them. Top-k keeps the k most likely tokens. Top-p, or nucleus sampling, keeps the smallest set whose probability mass exceeds p. Beam search keeps several partial sequences. None of these settings is a mind. Self-consistency samples several answers and keeps a majority. Search strategies keep candidates a checker can reject. Prompted intermediate reasoning can help some tasks and should not be read as the model's hidden computation.",
    keyConcepts: [
      { term: "Greedy, temperature, top-k, top-p", explanation: "These are decoding choices. Temperature 0 is often used to reduce randomness. It is not a universal proof of deterministic output across providers, batching, or hardware. Measure the system you call." },
      { term: "Beam search", explanation: "Beam search explores several hypotheses. It can help some structured tasks and can hurt others. It is not essential for all code generation." },
      { term: "Self-consistency", explanation: "A vote across samples. It is a statistic on outputs, not a view of internal reasoning." },
      { term: "Verification", explanation: "A check that does not depend on the same sample: a calculator, a schema, a unit test, a citation." },
    ],
    howItWorks: "The checklist scores the steps you select. The sample strings are a table written for the exercise. No model is sampled.",
    workedExamples: [{ title: "A bill that must match", label: "Precomputed samples", body: "Decompose hours and rate, then multiply outside the model. A second sample at any temperature is optional. The harmful step is demanding a private trace." }],
    visualNote: "The decoding diagram is a labeled tree: one greedy path, or several branches a checker can prune. Branches are named in text.",
    applications: "Invoices, eligibility, and puzzle-like tools want a checker. Ideation wants diversity. Open factual questions may use agreement and still need a source.",
    tradeoffs: "More samples and wider beams cost latency and money. They buy chances to recover, not truth.",
    bestPractices: ["Verify when a check exists.", "Match temperature to agreement or diversity.", "Log the procedure, not a demand for hidden thoughts.", "Re-measure decoding claims on the provider you use."],
    pitfalls: ["“Models don't reason” as a complete answer.", "“Chain-of-thought forces reasoning.”", "Temperature 0 as a universal determinism guarantee.", "Beam search as a default for every code task."],
    checkYourUnderstanding: ["What does nucleus sampling keep?", "Why is a vote not a proof?", "What should you check before saying temperature 0 is deterministic?"],
    whenToUse: "Use it to design a procedure you can defend.",
    whenNotToUse: "Do not use the sample table as model behavior.",
    productionConsiderations: "Put deterministic checks in the system when the domain allows them. Treat sampling settings as configuration to evaluate.",
  },
  educator: {
    whyTeach: "The public argument about reasoning is louder than the engineering choice about checks.",
    whatStudentsDo: "They select steps and a temperature.",
    evidencePrompts: ["Why a check rather than another sample?", "What is the vote evidence of?", "What did you refuse to ask the model to reveal?"],
    beforeClass: "Define greedy decoding in one sentence.",
    duringClass: "Students say whether the task is checkable before they build the workflow.",
    afterClass: "Contrast a calculator with a majority vote.",
    assignment: "For a task of their choosing, write the verifier or explain why none exists.",
    extension: "Read the self-consistency paper's claim as a performance result, not as a theory of mind.",
    relatedGames: "Alignment Arena asks which finished reply a policy prefers.",
  },
  discussionQuestions: ["Why is “LLMs don't reason” too blunt for this course?", "When is another sample the wrong purchase?", "What would make temperature 0 deterministic in a system you control?", "Why keep intermediate outputs public and checkable?"],
  nextConnection: { headline: "From a procedure to a preference", body: "A workflow can produce several replies. Alignment Arena asks which reply a stated policy should prefer, and why that is not one universal notion of good.", path: "Samples → a policy → a justified preference" },
};

export const alignmentTeaching: GameTeaching = {
  atAGlance: {
    tierExplanation: "Cognitive Core. The last core game makes the preference explicit.",
    recommendedLevel: "Intermediate.",
    timeExplanation: "About 25 minutes.",
    activityType: "Rank replies under printed weights for helpfulness, safety, and factuality.",
    masteryExplanation: "70% means the rankings matched the weighted rubric. It does not mean the student has aligned a model or that alignment is a single agreed target.",
    statusExplanation: "Playable Prototype. The weighted sum is computed. The scores are authored. No reward model is trained.",
  },
  whyThisGameExists: [
    "“Make it aligned” hides a disagreement. A reply can be more helpful and less safe, or fluent and false. Students need a policy they can point at.",
    "Lecture names — RLHF, reward model, preference data — arrive as a stack. The interaction that is actually learnable in a browser is a comparison: which reply wins under these weights, and what did the loser do better?",
    "The engineering use is preference data and evaluation. Modern stacks include supervised instruction tuning, reward modeling, reinforcement learning from human preferences, and direct preference optimization. PPO is one historical approach, not the only one. Constitutional AI and model-written feedback are further variants. None of them makes “good” a single scalar everyone shares.",
  ],
  bloomExplanation: "Analyze → Evaluate. Students compute a ranking and evaluate the trade-off in words. They do not train a policy.",
  misconceptions: [
    { statement: "Alignment is treated as one universal score of goodness.", howTheGameAddressesIt: "Weights change the winner. Students must name the dimension that decided it." },
    { statement: "A classroom ranking is treated as a trained reward model.", howTheGameAddressesIt: "The page computes a weighted sum of authored scores and says no model was trained." },
  ],
  assigning: { required: "Willingness to apply a printed weight.", helpful: "Promptsmith.", notRequired: "Reinforcement learning." },
  difficultyExplanation: "Intermediate: the math is a weighted sum. The judgment is naming the trade-off.",
  roundNotes: [
    { practicing: "Applying weights.", whyChosen: "The policy has to be read before taste takes over.", watchFor: "The largest total, and the dimension the loser won.", whatMattered: "A preference is a weighted comparison.", alternatives: "The reply that feels better can lose the policy." },
    { practicing: "Fluency versus factuality.", whyChosen: "Smooth prose hides missing truth.", watchFor: "The factuality weight.", whatMattered: "Tone is not evidence.", alternatives: "Choosing the smoother reply fails when factuality is weighted more." },
    { practicing: "Helpful and safe together.", whyChosen: "Refusal is not the opposite of usefulness when the request should be refused.", watchFor: "Whether safety is allowed to outrank completeness.", whatMattered: "The policy says what useful includes.", alternatives: "A more complete disallowed answer can be the worse preference." },
    { practicing: "A close call.", whyChosen: "Small gaps still have a winner, and a different weight could flip them.", watchFor: "Sensitivity.", whatMattered: "A close preference is still a policy choice.", alternatives: "Calling it a tie avoids the weight the round asked you to use." },
    { practicing: "Saying the preference in words.", whyChosen: "A click without a reason will not transfer.", watchFor: "The value that won and the value that lost.", whatMattered: "Justification is the learning, the points are the performance.", alternatives: "“It was better” does not name a trade-off." },
  ],
  scoringNarrative: "Five rounds, 10 or 0, for the reply with the highest weighted score. No partial credit for a close second. Hints subtract 1. Scores are authored. Mastery is 70% of the rankings, not agreement with a universal ethics.",
  transferExplanation: "Transfer is justifying a preference on a new pair without collapsing helpfulness, safety, and factuality into one word, “good.”",
  selfEvaluationQuestions: ["Can I compute a weighted preference?", "Can I name what the losing reply did better?", "Can I explain RLHF without claiming this page trained a model?", "Can I say why alignment is not one scalar?"],
  guide: {
    title: "Understanding alignment choices",
    overview: "Preference data records that one reply was preferred to another under some instruction. Instruction tuning supervises a model on demonstrations. A reward model can be trained to score replies the way those preferences did. RLHF then optimizes the model against that reward, often with a penalty that keeps it from drifting arbitrarily; PPO is one algorithm used for that step, not the only modern approach. Direct preference optimization trains from preferences without a separate reward model. Constitutional AI uses a written set of principles and model feedback. Helpfulness, harmlessness, and honesty pull apart. Reward hacking finds a score without the behavior you wanted. Sycophancy agrees with the user. Over-refusal refuses harmless requests. People and cultures disagree about the principles. This game only computes a weighted sum.",
    keyConcepts: [
      { term: "Preference and reward", explanation: "A comparison is not yet a reward model. A reward model is a learned score. This page prints the scores." },
      { term: "RLHF and alternatives", explanation: "Human preferences can train a reward and then a policy. Preference optimization can skip the explicit reward. Neither ends the argument about whose preferences were collected." },
      { term: "Failure modes", explanation: "Reward hacking, sycophancy, and over-refusal are different bugs. A single “aligned” badge hides which one you measured." },
      { term: "Disagreement", explanation: "A weight vector is a policy choice. Another community can write a different one." },
    ],
    howItWorks: "The browser multiplies authored helpfulness, safety, and factuality by the round's weights. No raters were recruited and no policy was updated.",
    workedExamples: [{ title: "Safety above completeness", label: "Educational preference simulation", body: "If safety has the largest weight, a refusal of a disallowed request can outrank a detailed answer. The detailed answer may still win helpfulness. Say that. Do not call the refusal universally good." }],
    visualNote: "The pipeline diagram is labeled preference, then reward, then optimization, with a note that this game stops at the weighted comparison.",
    applications: "Evaluation rubrics, red-team review, and preference collection all need the dimensions written down.",
    tradeoffs: "Optimizing one dimension depresses others. Collecting preferences concentrates someone's judgment. A rubric is more transparent and less complete than a trained reward.",
    bestPractices: ["Write the dimensions before you rank.", "Record what the loser did better.", "Separate a classroom rubric from a trained reward model.", "Expect disagreement."],
    pitfalls: ["One scalar called alignment.", "PPO as the only method.", "Treating authored scores as human data.", "Confusing refusal with safety in every case."],
    checkYourUnderstanding: ["What is the difference between a preference and a reward model?", "Name one alternative to PPO-style RLHF.", "Why can a helpful reply lose?"],
    whenToUse: "Use it when students need to defend a trade-off.",
    whenNotToUse: "Do not use the rankings as a dataset to train a model.",
    productionConsiderations: "Production alignment work needs a population, an evaluation, and a story about whose preferences count. This exercise is the arithmetic of a rubric.",
  },
  educator: {
    whyTeach: "Students otherwise leave with a slogan. The weights make the slogan into a calculation they can disagree with.",
    whatStudentsDo: "They select the higher weighted reply.",
    evidencePrompts: ["Which weight decided it?", "What did the other reply do better?", "Whose policy is this?"],
    beforeClass: "Define helpfulness, safety, and factuality as separate.",
    duringClass: "Change one weight on the board and ask who would flip.",
    afterClass: "Name RLHF, DPO, and Constitutional AI as a map, not as steps this game performed.",
    assignment: "Write a three-line rubric for a campus use case and rank two replies.",
    extension: "Discuss cultural variation without pretending the game sampled it.",
    relatedGames: "Ship-It Simulator turns to latency, cost, and reliability once a behavior exists to serve.",
  },
  discussionQuestions: ["Why is alignment not a single target?", "How can a rubric and a reward model disagree?", "What is over-refusal?", "Who is missing from a preference dataset?"],
  nextConnection: { headline: "From a preferred reply to a service", body: "Alignment Arena stops at the comparison. Ship-It Simulator asks what it costs to serve a model under a latency and reliability target.", path: "A policy for replies → a service that has to meet an SLO" },
};
