import type { GameTeaching } from "../../src/game-engine/schema.ts";

export const attentionTeaching: GameTeaching = {
  atAGlance: {
    tierExplanation: "Cognitive Core. Students read one attention step before they are asked to trust a diagram of a whole model.",
    recommendedLevel: "Introductory. Token Forge helps, but the only required idea is that the model sees a sequence of positions.",
    timeExplanation: "About 25 minutes. The arithmetic is small enough to recompute.",
    activityType: "Select the token that receives the highest simplified attention weight.",
    masteryExplanation: "70% means the selections matched the computed weights often enough for this activity. It does not mean the student can interpret a production attention map as the model's reasoning.",
    statusExplanation: "Playable Prototype. Gameplay, scoring, and this explanation work. The instructional design is still being refined. Prototype describes the software activity, not the importance of attention.",
  },
  whyThisGameExists: [
    "Attention is easy to gesture at and hard to read. Students hear that the model “looks at” the important word. The actual step is a comparison between a query and keys, then a weighted mix of values.",
    "A lecture formula is easy to copy and hard to use. This game computes a tiny scaled dot-product and softmax in the browser so the winner is a number, not a metaphor.",
    "The concept matters because every later representation in a transformer is built by mixing information across positions. Misreading that mix leads students to treat a heatmap as an explanation of reasoning. This page does not claim that.",
  ],
  bloomExplanation:
    "Bloom's taxonomy: Understand → Apply. Students identify query, key, and value, then apply the displayed weights to name the winning position. Later rounds ask them to notice that position and a second head can change the winner. They are not asked to derive multi-head attention from scratch.",
  misconceptions: [
    {
      statement: "A common misconception is that the previous token, or the grammatical object, automatically receives the attention.",
      howTheGameAddressesIt: "The weights are computed from authored vectors. The winner is whichever key matches the query, which may not be the word a reader expects.",
    },
    {
      statement: "Another misconception is that a heatmap is what the model is thinking.",
      howTheGameAddressesIt: "The page labels the figure as simplified weights on toy vectors. It is not a trained transformer and not a faithful trace of reasoning.",
    },
  ],
  assigning: {
    required: "Comfort reading a short sequence and comparing numbers.",
    helpful: "Having seen a token sequence in Token Forge, and the idea of a dot product.",
    notRequired: "Linear algebra beyond “larger match, larger score,” or any deep-learning framework.",
  },
  difficultyExplanation: "Introductory: the vectors are tiny and the question is which token wins. Students do not train heads or edit matrices.",
  roundNotes: [
    { practicing: "Reading a query-key match.", whyChosen: "The first pattern is small enough to check by eye.", watchFor: "The largest weight, not the most familiar word.", whatMattered: "The representation would mix the value at the winning position.", alternatives: "Choosing a grammatical neighbor ignores the score the head actually computed." },
    { practicing: "A pronoun-like dependency.", whyChosen: "Students expect coreference to be obvious. The head only has the match it was given.", watchFor: "Which noun the weights select.", whatMattered: "The wrong noun would contribute the wrong value.", alternatives: "A plausible referent that loses the dot product is not the winner of this head." },
    { practicing: "Polarity.", whyChosen: "Negation is a frequent failure mode when the contrast is under-weighted.", watchFor: "Whether the head emphasizes the negated word or the affirmative one.", whatMattered: "Those two positions support different meanings.", alternatives: "Picking the content word and skipping the polarity changes the representation." },
    { practicing: "Position.", whyChosen: "The same word in another place should be allowed to lose.", watchFor: "The index, not only the spelling.", whatMattered: "Positional information is part of what attention can use.", alternatives: "Treating identical strings as identical positions would answer a different model." },
    { practicing: "Two heads.", whyChosen: "Multi-head attention is several comparisons, not one arrow.", watchFor: "The head the round names.", whatMattered: "Another head may prefer a different token. That disagreement is the point.", alternatives: "Averaging the heads in your head hides the specialization the round is showing. Labels such as “syntax head” would be educational abstractions here, not universal categories of real transformers." },
  ],
  scoringNarrative: "Five rounds, 10 points each, 50 maximum. The token with the highest simplified weight on the named head scores 10. Any other token scores 0. There is no partial credit. Hints subtract 1 point each, down to 0. Best retry is kept. Mastery is 70% on this activity, not an ability to explain a production model.",
  transferExplanation: "Transfer is explaining why a different query, key, or head would change which information enters the representation, and refusing to call a simplified map the model's reasoning.",
  selfEvaluationQuestions: [
    "Can I say what query, key, and value each contribute?",
    "Can I explain why softmax does not change which score wins?",
    "Can I explain why a second head can prefer a different token?",
    "Can I say what this heatmap is not?",
  ],
  guide: {
    title: "Understanding attention",
    overview:
      "A transformer builds a contextual representation by letting positions exchange information. Scaled dot-product attention is the usual exchange. For a query matrix Q, key matrix K, and value matrix V, with key dimension d_k, the operation is softmax(Q K transpose / square root of d_k) times V. The fraction inside the softmax is a set of scores. Softmax turns scores into positive weights that sum to 1. The largest score remains the largest weight. Multiplying by V mixes the value vectors with those weights. This game shows one query against a few keys and asks which position wins. It computes that step. It does not run a transformer.",
    keyConcepts: [
      { term: "Query", explanation: "The query is the position asking for information. In a self-attention layer it comes from the same sequence as the keys." },
      { term: "Key", explanation: "Each key is what a position offers to be matched. The score is the match between query and key, scaled so the values do not grow without bound as the dimension grows." },
      { term: "Value", explanation: "The value is the information that gets mixed in if the key wins weight. Matching a key and copying a value are different roles." },
      { term: "Heads and masks", explanation: "Several heads can use different projections, so one layer can emphasize different relationships. A causal mask sets future positions to a score that softmax will drive toward zero, which is how a decoder avoids reading tokens that have not been generated. This game's later round shows two authored heads. It does not apply a causal mask unless a round says so." },
      { term: "Position", explanation: "Attention by itself compares content. Models add positional information so order can matter. A head can learn to use it. That is not the same as a universal “position head” in every model." },
    ],
    howItWorks: "Scores and softmax weights are computed in the browser from the vectors in the round: query dot key, divided by the scale, then softmax. The vectors are hand-authored. There is no trained model and no claim that these weights match any production attention pattern.",
    workedExamples: [
      { title: "One query, three keys", label: "Simplified educational calculation", body: "If the scaled scores are 1, 0, and -1, softmax assigns the most weight to the first key. You do not need the exact percentages to know the winner. The percentages are there so the ordering is checkable." },
    ],
    visualNote: "The attention figure is a labeled weight list, not a color-only heatmap. The selected token is also named in text.",
    applications: "Attention is why a token can depend on an earlier definition, a later qualifier, or a distant name. Reading one head of one layer is a clue. It is not an explanation of the whole model.",
    tradeoffs: "More heads and more layers can represent more relationships and cost more compute. A single visualized head is easier to teach and easier to over-interpret.",
    bestPractices: ["Name the head and the layer you are looking at.", "Treat weights as a mix of values, not as a sentence about intent.", "Check whether position was part of the input.", "Prefer a recomputed toy example before a production heatmap."],
    pitfalls: ["Calling a head a syntax head or a coreference head as if those were universal modules.", "Equating the largest weight with a human explanation.", "Ignoring the scale and comparing raw dot products across different dimensions."],
    checkYourUnderstanding: ["What does the square-root scale do to the scores?", "Why can two heads disagree?", "What would a causal mask change?"],
    whenToUse: "Use this when students need the formula to become a winner they can point at.",
    whenNotToUse: "Do not use it as evidence of what a deployed model attends to.",
    productionConsiderations: "Production attention maps, when available, are still not a faithful account of reasoning. Use them as a debugging hint and evaluate the system's outputs separately.",
  },
  educator: {
    whyTeach: "Without a computed example, attention remains a metaphor. The metaphor then contaminates later topics such as retrieval and explanation.",
    whatStudentsDo: "They select the winning token. The weights update from the same vectors every learner sees.",
    evidencePrompts: ["Which term in the formula decided the winner?", "What would a different query have changed?", "Why is this not the model's reasoning?"],
    beforeClass: "Write the formula once and name Q, K, V, and d_k.",
    duringClass: "Have students point at the weight before they click.",
    afterClass: "Ask what a second head is for, without inventing a universal job title for it.",
    assignment: "Give a new three-token vector set and ask students to name the winner before using a calculator.",
    extension: "Discuss what a causal mask would hide, without pretending this game applied one.",
    relatedGames: "Token Forge produced the sequence. Context Compression decides which of those positions are worth keeping.",
  },
  discussionQuestions: ["Why is the largest score still the largest weight after softmax?", "What is lost if we describe attention as looking at the important word?", "Why are names like syntax head risky?", "When would position change the winner even if the word is the same?"],
  nextConnection: { headline: "From mixing positions to spending them", body: "Attention mixes information across the sequence. Context Compression asks which of those tokens you can afford to keep.", path: "Tokens → attention over positions → a context budget" },
};

export const contextTeaching: GameTeaching = {
  atAGlance: {
    tierExplanation: "Cognitive Core. The sequence now has a budget.",
    recommendedLevel: "Introductory, after students accept that length is counted in tokens.",
    timeExplanation: "About 20 minutes.",
    activityType: "Choose what to keep under a token budget without dropping a required fact.",
    masteryExplanation: "70% means the selections met the budget and the relevance rules on these cases. It is not a general certificate in summarization.",
    statusExplanation: "Playable Prototype. The budget arithmetic works. Summary text is authored. The activity is still being refined. That status is about the software, not about whether context limits matter.",
  },
  whyThisGameExists: [
    "Students hear “the context window is  the limit” and then try to solve it by making text shorter. Shorter can delete the negation, the deadline, or the number the answer depends on.",
    "A lecture can define extractive and abstractive compression. It rarely makes the student add the token costs and watch a must-keep span fall out.",
    "In systems, this decision is how retrieval packs a prompt, how a thread is summarized, and how a tool result is truncated. The engineering question is relevance under a constraint.",
  ],
  bloomExplanation: "Understand → Apply. Students distinguish extractive, abstractive, and hierarchical strategies, then apply a budget and a must-keep rule to a passage.",
  misconceptions: [
    { statement: "The goal is often mistaken for “make it shorter.”", howTheGameAddressesIt: "A short option fails when it drops a required fact, even if it is under the budget." },
    { statement: "A summary is assumed to be a model generation.", howTheGameAddressesIt: "Abstractive text in this game is prewritten. The page says so." },
  ],
  assigning: { required: "The idea of a token as a unit of length.", helpful: "Token Forge.", notRequired: "A summarization model or a specific vendor context length." },
  difficultyExplanation: "Introductory: the numbers to add are on the spans. Students are not writing a compressor.",
  roundNotes: [
    { practicing: "Extractive selection of a required fact.", whyChosen: "The simplest success case is a fact that fits.", watchFor: "The span the task needs, not the background.", whatMattered: "The original wording of the rule survived inside the budget.", alternatives: "Keeping colorful background can crowd out the rule." },
    { practicing: "A negation.", whyChosen: "Deleting “not” is a meaning change that still looks like compression.", watchFor: "Polarity words.", whatMattered: "A fluent shorter text can invert the policy.", alternatives: "Any summary that drops the negation is under budget and wrong." },
    { practicing: "Must-keep facts that do not fit as quotes.", whyChosen: "Extraction has a hard stop when the quotes themselves overflow.", watchFor: "Whether the abstract still carries those facts.", whatMattered: "Strategy has to change when faithful quotes do not fit.", alternatives: "Cutting until it fits can be the failure mode." },
    { practicing: "Hierarchical notes.", whyChosen: "Some sources have a decision and supporting detail. The budget may hold only the decision.", watchFor: "What the later step will need to recover.", whatMattered: "Hierarchy is a structure, not just a shorter paragraph.", alternatives: "A flat extract preserves detail and breaks the budget." },
    { practicing: "Relevance over raw length.", whyChosen: "The last round makes the objective explicit.", watchFor: "The task, not the character count.", whatMattered: "The downstream answer still has its evidence.", alternatives: "The shortest option can be the least usable." },
  ],
  scoringNarrative: "Five rounds, 10 or 0. A round scores 10 only if the strategy stays inside the token budget, meets the relevance minimum, and does not drop a must-keep fact. Hints subtract 1, to a floor of 0. Best retry is kept. Mastery is 70% of these cases.",
  transferExplanation: "Transfer is naming what you kept, what you removed, and why, on a passage this game did not show.",
  selfEvaluationQuestions: ["Can I explain extractive versus abstractive compression?", "Can I say when shorter is worse?", "Can I add a token budget by hand?", "Can I explain what this page does not generate?"],
  guide: {
    title: "Understanding context compression",
    overview: "A context window is a token budget shared by instructions, evidence, and the answer the model still has to generate. Compression is how you decide what remains. Extractive compression keeps original spans. Abstractive compression rewrites them. Hierarchical summarization keeps a coarse layer and can point back to detail. Chunking, used again in retrieval, is a cousin decision: where the boundaries fall. None of these is “make it shorter” unless the task-relevant information survives.",
    keyConcepts: [
      { term: "Token budget", explanation: "Input tokens and reserved output tokens both spend the window. A number quoted for a product is not timeless. This game uses the budget printed on the round." },
      { term: "Extractive compression", explanation: "You select spans. The words stay the source's words. Faithfulness is high. Fit is not guaranteed." },
      { term: "Abstractive compression", explanation: "You rewrite. The result can fit and can also change a number or a negation. In this game the rewrite is authored ahead of time." },
      { term: "Information loss", explanation: "Loss is a missing or altered fact the task needed. A shorter text can have more loss." },
    ],
    howItWorks: "Sums, budget checks, and relevance totals are computed from the numbers on the spans. Summaries are prewritten. No model is called.",
    workedExamples: [{ title: "A 40-token budget", label: "Deterministic arithmetic", body: "If two must-keep spans cost 18 and 15, they fit in 40. A third background span of 20 does not. The decision is which span the task required, not which paragraph was longest." }],
    visualNote: "The budget meter compares used tokens with the limit and names must-keep spans in text, not by color alone.",
    applications: "Thread summarization, retrieval packing, tool-result truncation, and meeting notes all force this choice.",
    tradeoffs: "Quotes are auditable and bulky. Summaries are compact and risky. Hierarchies add a way back to detail and add machinery.",
    bestPractices: ["Mark facts the task cannot lose before you cut.", "Reserve tokens for the answer.", "Check negations, dates, and names after compression.", "Do not cite a vendor window without a date."],
    pitfalls: ["Equating brevity with quality.", "Trusting an abstract that was never checked against the source.", "Using a stale context-window number from a slide."],
    checkYourUnderstanding: ["When is extraction not available?", "What is information loss if the text is grammatical?", "Why split input and output budget?"],
    whenToUse: "Use it when students need a budget they can add up.",
    whenNotToUse: "Do not present the prewritten summaries as model output.",
    productionConsiderations: "Evaluate compressed prompts on task success, not only on tokens saved. Re-measure when the model or the window changes.",
  },
  educator: {
    whyTeach: "Context errors look like model errors. Often the needed sentence was deleted upstream.",
    whatStudentsDo: "They pick a strategy and, when asked, the spans to keep.",
    evidencePrompts: ["What did you keep?", "What did you drop?", "Why was the short option wrong?"],
    beforeClass: "Define token budget with one numeric example.",
    duringClass: "Students predict whether the must-keep spans fit before submitting.",
    afterClass: "Compare a deletion and a rewrite of the same negation.",
    assignment: "Give a policy paragraph and a question. Ask which sentence must survive and why.",
    extension: "Ask how retrieval is a form of selective context construction.",
    relatedGames: "Promptsmith will put the remaining context inside an instruction. Retrieval Lab chooses the chunks.",
  },
  discussionQuestions: ["When would you refuse to compress further?", "How can a summary be under budget and still harmful?", "Why are product context sizes a poor thing to memorize?"],
  nextConnection: { headline: "From a budget to a specification", body: "Once the evidence fits, Promptsmith asks how the instruction around that evidence should be written.", path: "Token budget → what remains → the task specification" },
};

export const promptsmithTeaching: GameTeaching = {
  atAGlance: {
    tierExplanation: "Cognitive Core. The task itself becomes the object of design.",
    recommendedLevel: "Intermediate. Students should already know that extra tokens have a cost.",
    timeExplanation: "About 25 minutes.",
    activityType: "Match a prompting strategy to a failure mode.",
    masteryExplanation: "70% means the chosen strategies fit these authored cases. It is not mastery of prompt engineering as a profession.",
    statusExplanation: "Playable Prototype. Outcomes are authored. No model is called. The activity is under refinement.",
  },
  whyThisGameExists: [
    "Students often hunt for a magical phrase. The failure in front of them is usually a missing specification: no schema, no example, no check, or no constraint.",
    "Prompting is hard to learn from advice lists because the advice conflicts until you name the failure. A format error and a tone error want different changes.",
    "In engineering, the prompt is an interface to a probabilistic model. It is not a window into how the model thinks, and this game never asks for hidden chain-of-thought.",
  ],
  bloomExplanation: "Apply → Analyze. Students apply a strategy and analyze which part of the specification, not which adjective, made the task more reliable.",
  misconceptions: [
    { statement: "Prompting is sometimes described as understanding how models think.", howTheGameAddressesIt: "The lesson is specification and interface design. Hidden reasoning is neither shown nor requested." },
    { statement: "A longer prompt is assumed to be a better prompt.", howTheGameAddressesIt: "Cost and failure labels are printed. A cheaper strategy can be the best fit when it still meets the task." },
  ],
  assigning: { required: "Ability to read a task and say what would count as a failed answer.", helpful: "Context Compression.", notRequired: "A live model or a prompt-library subscription." },
  difficultyExplanation: "Intermediate: students compare strategies. They do not search an open-ended space of wording.",
  roundNotes: [
    { practicing: "Output format.", whyChosen: "Extraction fails quietly when the answer is fluent and unparseable.", watchFor: "The fields the caller must read.", whatMattered: "A schema makes the failure detectable.", alternatives: "A persona without a schema can sound helpful and omit a field." },
    { practicing: "Decomposition.", whyChosen: "Multi-step quantities hide errors inside one instruction.", watchFor: "The check between steps.", whatMattered: "An explicit step can be verified.", alternatives: "One vague instruction is shorter and harder to debug." },
    { practicing: "Role or voice.", whyChosen: "Voice matters for some tasks and is irrelevant for others.", watchFor: "Whether the requirement is tone or truth.", whatMattered: "A role steers style. It does not enforce a policy.", alternatives: "Adding a persona to a parsing task spends tokens on the wrong problem." },
    { practicing: "Few-shot examples.", whyChosen: "A rare label set is often easier to show than to define.", watchFor: "Whether the examples are the pattern, not decoration.", whatMattered: "Examples spend context to stabilize an unusual format.", alternatives: "A definition alone can drift. Examples of the wrong pattern teach the wrong pattern." },
    { practicing: "Quality against cost.", whyChosen: "The last round refuses both “always elaborate” and “always short.”", watchFor: "The failure mode that is still open.", whatMattered: "Reliability per token, not eloquence.", alternatives: "The richest prompt can be wasteful. The cheapest can be unusable." },
  ],
  scoringNarrative: "Five rounds. Best strategy 10, acceptable 6, poor 0. Hints subtract 1, floor 0. The metrics on a card are authored, not a live call. Mastery is 70%.",
  transferExplanation: "Transfer is explaining which change made a new task specification more reliable, and what it cost, without claiming the wording revealed the model's thoughts.",
  selfEvaluationQuestions: ["Can I name the failure mode before the strategy?", "Can I say when a schema beats a role?", "Can I explain few-shot prompting without calling it magic?", "Can I refuse a request for hidden chain-of-thought?"],
  guide: {
    title: "Understanding prompt design",
    overview: "A prompt specifies a task for a probabilistic model. Useful pieces include the instruction, the context, examples, constraints, and the output format. Few-shot prompting shows the pattern. A role can set voice when voice is the requirement. Decomposition breaks a job into checks. Evaluation tells you whether the result is usable. Iterative refinement is changing one of those pieces and measuring again. Prompt injection is the risk that untrusted text inside the context tries to override the instruction. None of this is a theory of hidden cognition.",
    keyConcepts: [
      { term: "Instruction and context", explanation: "The instruction says what to do. The context is the evidence. Mixing them without a boundary makes injection easier." },
      { term: "Few-shot examples", explanation: "Examples demonstrate a pattern. They are not proof the model understood a rule, and they spend tokens." },
      { term: "Structured output", explanation: "A schema, a table, or a constrained format makes the answer checkable by a program." },
      { term: "Decomposition", explanation: "Separate steps with a check beat one opaque request when the task has intermediate quantities." },
    ],
    howItWorks: "Cards are authored comparisons. No model is called. Visible reasoning steps, where a round mentions them, are part of the specification, not a claim about internal computation.",
    workedExamples: [{ title: "An invoice schema", label: "Authored outcome", body: "A prompt that asks for a friendly summary can omit the total. A prompt that names the fields fails detectably when a field is missing. The second one is a better interface for a parser." }],
    visualNote: "The prompt anatomy diagram labels instruction, context, examples, and output format as separate regions with text, not color alone.",
    applications: "Extraction, classification, support replies, and tool calls are all specifications with different failure modes.",
    tradeoffs: "Examples and schemas add tokens and often add reliability. Roles add voice and rarely add parseability. More text is not a strategy.",
    bestPractices: ["Name the failure you are designing against.", "Separate untrusted context from the instruction.", "Evaluate on the task, not on a single impressive demo.", "Do not ask the model to reveal private reasoning."],
    pitfalls: ["Magical wording.", "A persona standing in for a schema.", "Treating chain-of-thought text as a faithful trace.", "Copying a prompt that was written for a different model without measuring."],
    checkYourUnderstanding: ["What does few-shot prompting spend, and what might it buy?", "Why is a schema an interface?", "What is prompt injection in one sentence?"],
    whenToUse: "Use it to practice systematic changes.",
    whenNotToUse: "Do not use authored win rates as evidence about a live model.",
    productionConsiderations: "Version prompts, evaluate them on a set, and watch for injection from retrieved or user text. Re-test when the model changes.",
  },
  educator: {
    whyTeach: "Prompt advice on the internet conflicts. Students need a way to choose a change on purpose.",
    whatStudentsDo: "They select a strategy and read the authored quality and cost.",
    evidencePrompts: ["Which part of the specification changed?", "What failure did it prevent?", "What did it cost?"],
    beforeClass: "Show one unparseable extraction.",
    duringClass: "Students name the failure before they click.",
    afterClass: "Try one schema on a real model if you have access, and compare. Differences are expected.",
    assignment: "Rewrite a vague prompt into instruction, context, and output format. State what you would measure.",
    extension: "Add an untrusted paragraph that tries to override the instruction, and discuss the boundary.",
    relatedGames: "Reasoning Reactor designs the procedure around a sample. Alignment Arena judges the reply.",
  },
  discussionQuestions: ["Why is prompt design closer to interface design than to spell-casting?", "When are examples worth the tokens?", "Why should visible reasoning text not be treated as hidden computation?", "How does untrusted context change the specification?"],
  nextConnection: { headline: "From the interface to adaptation", body: "Promptsmith changes the request. Gradient Playground is about changing the model, and about the evidence a loss curve does and does not provide.", path: "Specification → optional adaptation → still evaluate the task" },
};
