import type { GameDefinition } from "../../src/game-engine/schema.ts";

const scoreRule =
  "10 points if every needed tool and control is selected and no harmful tool or control is selected. Otherwise 0. Each hint subtracts 1 point, to a floor of 0.";

const agentArchitect: GameDefinition = {
  id: "agent-architect",
  status: "prototype",
  title: "Agent Architect",
  tier: 2,
  order: 9,
  summary: "Design an agent loop with tools, permissions, checks, and a way to stop.",
  purpose: "Show that an agent is a controlled loop, not a model with every tool turned on.",
  whyItMatters: "Tool access is authority. Memory, retries, and escalation decide whether a mistake stays small.",
  learningObjectives: [
    "Select only the tools the task needs.",
    "Separate read tools from tools that change the world.",
    "Add verification before a side effect.",
    "Add a human escalation path and a stopping rule.",
  ],
  concepts: ["Agent loop", "Tool selection", "Permissions", "State", "Memory", "Planning", "Verification", "Retries", "Graceful degradation", "Human escalation"],
  bloomLevels: ["apply", "analyze", "evaluate"],
  prerequisites: [],
  estimatedMinutes: 25,
  difficulty: "advanced",
  masteryThreshold: 70,
  misconception: "An agent is not “an LLM plus every API.” Unbounded memory and unbounded retries are design choices with failure modes.",
  reflectionPrompt: "Which tool in a system you use should require a human before it runs, and what should happen if that human is unavailable?",
  workedExample: {
    title: "A refund lookup that cannot send mail",
    steps: [
      "The question can be answered with a read-only order tool.",
      "A send-email tool is a side effect the task did not request.",
      "Verify the order id before you trust the tool result.",
      "If the tool errors twice, stop and escalate instead of looping.",
    ],
  },
  furtherReadingIds: ["yao2023tot", "huyen2022dmls"],
  implementation: {
    type: "deterministic-simulation",
    label: "Agent-loop checklist",
    whatIsReal: "The scoring of needed and harmful tools and controls.",
    whatIsSimulated: "No agent runs and no tools are called.",
  },
  rounds: [
    {
      id: "refund-status",
      title: "Round 1 · Read a refund",
      concept: "Least privilege",
      learnerTask: "Give the agent the order lookup and a verifier. Do not give it email or a payment tool.",
      expectedReasoning: "The user asked for status. A write tool is unused authority.",
      scenario: "“Where is my refund?” The order system has a read API. Nothing in the request asks you to contact the customer or move money.",
      hints: [
        "Start from the question the user asked.",
        "A tool that sends email is a side effect.",
        "Needed: order lookup and verify-the-id. Harmful if selected: send email and issue refund.",
      ],
      scoringRule: scoreRule,
      explanation: "Permissions are part of the agent even when the model is capable of calling a richer API. Capability is not authorization.",
      feedbackCorrect: "The loop can answer the status question and cannot move money.",
      feedbackIncorrect: "Remove tools that change the world. Keep the lookup and the check.",
      interaction: {
        type: "agent",
        prompt: "Choose tools and controls.",
        goal: "Tell the user the refund status for an order id they provide.",
        tools: [
          { id: "lookup", label: "Read order status", description: "Read-only order API.", needed: true, harmful: false },
          { id: "email", label: "Send email", description: "Messages the customer.", needed: false, harmful: true },
          { id: "pay", label: "Issue a refund", description: "Moves money.", needed: false, harmful: true },
        ],
        controls: [
          { id: "verify", label: "Verify the order id format before the call", description: "Reject malformed ids.", needed: true, harmful: false },
          { id: "loop", label: "Retry forever on errors", description: "No stopping rule.", needed: false, harmful: true },
        ],
      },
    },
    {
      id: "calendar",
      title: "Round 2 · A write that is actually requested",
      concept: "Side effects with confirmation",
      learnerTask: "Allow the calendar write only with a confirmation step and an escalation when the room is taken.",
      expectedReasoning: "The user asked to book a room, so the write tool is needed. It still needs a confirmation and a stop if the room is unavailable.",
      scenario: "Book seminar room B for Thursday at 15:00 if it is free. If it is not free, ask the user instead of picking another room silently.",
      hints: [
        "This task really does need a write.",
        "Silent substitution of another room is the harmful control.",
        "Needed tools: check availability and create the event. Needed controls: confirm with the user, escalate if taken.",
      ],
      scoringRule: scoreRule,
      explanation: "A justified side effect still sits behind a check. Graceful degradation here means asking, not inventing a different booking.",
      feedbackCorrect: "The booking can happen, and only after a confirmation, with a stop when the room is taken.",
      feedbackIncorrect: "Do not include the control that silently books a different room.",
      interaction: {
        type: "agent",
        prompt: "Choose tools and controls for the booking.",
        goal: "Book room B at the requested time or stop and ask.",
        tools: [
          { id: "check", label: "Check room availability", description: "Read the calendar.", needed: true, harmful: false },
          { id: "book", label: "Create the event", description: "Writes one event.", needed: true, harmful: false },
          { id: "mail-all", label: "Email the whole campus", description: "Unrelated broadcast.", needed: false, harmful: true },
        ],
        controls: [
          { id: "confirm", label: "Show the event and wait for confirmation", description: "A human confirms the write.", needed: true, harmful: false },
          { id: "escalate", label: "If the room is taken, ask the user", description: "Do not guess another room.", needed: true, harmful: false },
          { id: "silent", label: "Silently book any free room", description: "Changes the request.", needed: false, harmful: true },
        ],
      },
    },
    {
      id: "memory",
      title: "Round 3 · Memory with a boundary",
      concept: "State and memory",
      learnerTask: "Keep task state for this session. Do not write unconstrained long-term memory of the student's personal details.",
      expectedReasoning: "The multi-step form needs short-term state. A permanent profile of health details is not authorized by the task.",
      scenario: "The agent helps a student fill a public lab-safety form across several turns. It must remember the incomplete answers for this session only.",
      hints: [
        "Session state and permanent memory are different tools.",
        "The harmful tool stores health details indefinitely.",
        "Needed: session state and a review step before submit.",
      ],
      scoringRule: scoreRule,
      explanation: "Memory is a product decision about retention. An agent that remembers everything is harder to explain, delete, and trust.",
      feedbackCorrect: "The form can continue across turns without a permanent personal record.",
      feedbackIncorrect: "Keep session state. Do not enable the permanent personal-memory tool.",
      interaction: {
        type: "agent",
        prompt: "Choose memory and controls.",
        goal: "Finish one lab-safety form in this session.",
        tools: [
          { id: "session", label: "Session scratchpad", description: "Forgotten when the session ends.", needed: true, harmful: false },
          { id: "permanent", label: "Permanent personal memory", description: "Stores answers, including health notes, forever.", needed: false, harmful: true },
          { id: "policy", label: "Read the public lab policy", description: "Read-only policy page.", needed: true, harmful: false },
        ],
        controls: [
          { id: "review", label: "Show the form before submit", description: "The student sees the payload.", needed: true, harmful: false },
          { id: "autosubmit", label: "Submit as soon as every field is non-empty", description: "No review.", needed: false, harmful: true },
        ],
      },
    },
    {
      id: "degrade",
      title: "Round 4 · Degrade when search fails",
      concept: "Graceful degradation",
      learnerTask: "If search fails, answer from the course FAQ and say the search was unavailable. Do not invent a web result.",
      expectedReasoning: "A failed tool should change the plan. Inventing a result is the harmful control. Unlimited retries are also harmful.",
      scenario: "The course assistant searches the syllabus site. The site times out. Students still need the attendance rule, which is in a local FAQ.",
      hints: [
        "A backup source is part of the plan, not an afterthought.",
        "Saying that search failed is required.",
        "Needed: FAQ tool, disclose-the-failure, one capped retry. Harmful: invent a citation, retry forever.",
      ],
      scoringRule: scoreRule,
      explanation: "Graceful degradation is a designed second path. It includes telling the user which path ran.",
      feedbackCorrect: "The agent can fall back to the FAQ, say so, and stop retrying.",
      feedbackIncorrect: "Inventing a search result is not a fallback. Turn that control off.",
      interaction: {
        type: "agent",
        prompt: "Design the failure path.",
        goal: "Answer the attendance question even if the syllabus site times out.",
        tools: [
          { id: "search", label: "Search the syllabus site", description: "May time out.", needed: true, harmful: false },
          { id: "faq", label: "Local course FAQ", description: "Contains the attendance rule.", needed: true, harmful: false },
        ],
        controls: [
          { id: "disclose", label: "Tell the user when search did not run", description: "Name the source that was used.", needed: true, harmful: false },
          { id: "cap", label: "One retry, then stop", description: "A bounded retry.", needed: true, harmful: false },
          { id: "invent", label: "If search fails, write a plausible quotation", description: "Fabricates a source.", needed: false, harmful: true },
          { id: "forever", label: "Retry until the site returns", description: "No stopping rule.", needed: false, harmful: true },
        ],
      },
    },
    {
      id: "plan",
      title: "Round 5 · Plan, act, check",
      concept: "Planning and verification",
      learnerTask: "Require a written plan, a single shell tool limited to the project directory, and a test run before the agent claims success.",
      expectedReasoning: "The coding task needs a plan and a test. A general-purpose shell without a directory limit is the harmful tool.",
      scenario: "An assignment bot may edit one student repository and must run the provided tests. It may not touch other directories.",
      hints: [
        "Planning is a control, not a second model.",
        "The scoped editor is needed. The unrestricted shell is harmful.",
        "Needed controls: write the plan, run tests, escalate if tests fail twice.",
      ],
      scoringRule: scoreRule,
      explanation: "A plan is useful when it is checked against an observable result, here the test command. The plan is not evidence of hidden reasoning.",
      feedbackCorrect: "The agent is limited to the repository, and it cannot claim success without the tests.",
      feedbackIncorrect: "Drop the unrestricted shell. Keep the plan, the scoped editor, and the test gate.",
      interaction: {
        type: "agent",
        prompt: "Choose the coding agent's authority.",
        goal: "Patch the repository so the provided tests pass.",
        tools: [
          { id: "editor", label: "Edit files inside the repo", description: "Path is confined to the project.", needed: true, harmful: false },
          { id: "shell", label: "Unrestricted shell", description: "Any command on the machine.", needed: false, harmful: true },
          { id: "tests", label: "Run the assignment tests", description: "The observable check.", needed: true, harmful: false },
        ],
        controls: [
          { id: "plan", label: "Write a short plan before editing", description: "A public plan the student can read.", needed: true, harmful: false },
          { id: "gate", label: "Do not claim success unless tests pass", description: "Verification.", needed: true, harmful: false },
          { id: "escalate", label: "After two failed test runs, stop and ask", description: "Bounded loop with escalation.", needed: true, harmful: false },
        ],
      },
    },
  ],
};

export default agentArchitect;
