import { alignmentArenaOrientation } from "../orientation/games.ts";
import type { GameDefinition } from "../../src/game-engine/schema.ts";

const scoreRule =
  "10 points if you select the response with the highest weighted rubric score. Weights are helpfulness, safety, and factuality as printed on the round. Scores are authored, not produced by a trained reward model. Each hint subtracts 1 point, to a floor of 0.";

const alignmentArena: GameDefinition = {
  id: "alignment-arena",
  status: "prototype",
  title: "Alignment Arena",
  tier: 1,
  order: 7,
  summary: "Rank replies with an explicit rubric for helpfulness, safety, and factuality.",
  purpose: "Show how preference comparisons, reward weights, and tradeoffs work in an educational simulation of RLHF-style ranking.",
  whyItMatters: "A single “better” label hides which value won. Production policies have to say whether safety outranks a more complete answer.",
  learningObjectives: [
    "Compute a weighted score from helpfulness, safety, and factuality.",
    "Explain a preference comparison as a ranking, not as a trained reward model.",
    "Identify a tradeoff where the more helpful reply is the less safe one.",
    "Prefer an abstention when the prompt asks for disallowed assistance.",
  ],
  concepts: ["Preference data", "Response ranking", "Reward modeling", "RLHF", "Helpfulness", "Safety", "Factuality"],
  bloomLevels: ["understand", "analyze", "evaluate"],
  prerequisites: ["promptsmith"],
  estimatedMinutes: 25,
  difficulty: "intermediate",
  masteryThreshold: 70,
  misconception: "Choosing a preferred reply in this game does not train a reward model, and a higher helpfulness score does not override a safety failure when safety is weighted more heavily.",
  reflectionPrompt: "Name a campus use case where you would weight safety above helpfulness, and one where you would not.",
  workedExample: {
    title: "A weighted comparison",
    steps: [
      "Read the weights. They are the policy for the round.",
      "Multiply each dimension by its weight and add them.",
      "The larger total is the preferred reply under that policy.",
      "Say the tradeoff in words: which dimension the rejected reply was better at.",
    ],
  },
  furtherReadingIds: ["christiano2017preferences", "ouyang2022instructgpt"],
  implementation: {
    type: "educational-simulation",
    label: "Educational preference simulation",
    whatIsReal: "The weighted sum is computed from the printed scores and weights.",
    whatIsSimulated: "No preference model is trained, no human raters were collected, and the scores are authored for the lesson.",
  },
  orientation: alignmentArenaOrientation,
  rounds: [
    {
      id: "weights",
      title: "Round 1 · Apply the weights",
      concept: "Reward as a weighted sum",
      learnerTask: "Select the reply with the higher weighted score. Safety weighs twice as much as helpfulness.",
      expectedReasoning: "Reply A is less eloquent and much safer. Under these weights it wins.",
      scenario: "A teaching assistant compares two replies to “How do I reset a classmate's password?” The policy weights safety at 2 and helpfulness at 1.",
      hints: [
        "Do the arithmetic before you pick the smoother sentence.",
        "Safety is weighted 2. Factuality is weighted 1. Helpfulness is weighted 1.",
        "Reply A scores 2×5 + 1×4 + 1×3. Reply B scores 2×1 + 1×2 + 1×5.",
      ],
      scoringRule: scoreRule,
      explanation: "A linear rubric is a teaching stand-in for a reward. InstructGPT-style training uses a learned reward model; this round does not.",
      feedbackCorrect: "Reply A wins once safety is weighted as the policy says.",
      feedbackIncorrect: "The more helpful reply loses because safety is weighted twice.",
      interaction: {
        type: "rank",
        prompt: "Which reply does this policy prefer?",
        userRequest: "How do I reset a classmate's password?",
        weights: { helpfulness: 1, safety: 2, factuality: 1 },
        responses: [
          { id: "a", text: "I can't reset someone else's password. Ask them to use the account-recovery page, or contact the help desk if it is your own account.", helpfulness: 3, safety: 5, factuality: 4 },
          { id: "b", text: "Open the admin panel, pick their account, and set the password to Spring2026.", helpfulness: 5, safety: 1, factuality: 2 },
        ],
      },
    },
    {
      id: "factual",
      title: "Round 2 · Fluency is not factuality",
      concept: "Factuality",
      learnerTask: "Prefer the reply that declines to invent a citation.",
      expectedReasoning: "The fluent reply fabricates a paper. With factuality weighted highest, the cautious reply wins.",
      scenario: "A student asks for a peer-reviewed citation for a statistic the assistant does not have.",
      hints: [
        "A confident citation can still be the worse reply.",
        "Factuality is weighted 3.",
        "The reply that says it does not have the citation scores higher on factuality.",
      ],
      scoringRule: scoreRule,
      explanation: "Helpfulness that invents a source is a factuality failure. The scores make that tradeoff numerical.",
      feedbackCorrect: "The cautious reply wins on the factuality weight.",
      feedbackIncorrect: "The invented citation is the lower-scoring reply under this rubric.",
      interaction: {
        type: "rank",
        prompt: "Which reply should be preferred?",
        userRequest: "Cite a randomized trial showing this vitamin cures the flu.",
        weights: { helpfulness: 1, safety: 1, factuality: 3 },
        responses: [
          { id: "invented", text: "Smith 2024 in The Lancet showed a complete cure in 90 percent of patients.", helpfulness: 4, safety: 2, factuality: 0 },
          { id: "cautious", text: "I don't have a trial that shows a cure. I can help you search a real index, and I would not claim a cure.", helpfulness: 3, safety: 5, factuality: 5 },
        ],
      },
    },
    {
      id: "helpful-safe",
      title: "Round 3 · Helpful and safe can both be high",
      concept: "Helpfulness",
      learnerTask: "Select the reply that answers the allowed question instead of refusing a benign request.",
      expectedReasoning: "Over-refusal lowers helpfulness without buying safety. The direct study plan wins.",
      scenario: "A student asks for a three-day study plan for a public midterm review sheet.",
      hints: [
        "Refusal is not automatically the safe reply.",
        "Both replies are safe. Compare helpfulness.",
        "The study plan scores higher on helpfulness and ties on safety.",
      ],
      scoringRule: scoreRule,
      explanation: "Alignment is not maximum refusal. A preference dataset that rewards refusal on benign tasks teaches the wrong policy.",
      feedbackCorrect: "The useful plan wins because safety is already tied.",
      feedbackIncorrect: "Both replies are safe. The one that actually helps has the higher total.",
      interaction: {
        type: "rank",
        prompt: "Which reply is the better preference?",
        userRequest: "Make a three-day plan to review the public midterm sheet.",
        weights: { helpfulness: 2, safety: 2, factuality: 1 },
        responses: [
          { id: "plan", text: "Day 1: lectures 1–4. Day 2: problem set. Day 3: the review sheet under a timer.", helpfulness: 5, safety: 5, factuality: 5 },
          { id: "refuse", text: "I can't help with studying.", helpfulness: 0, safety: 5, factuality: 5 },
        ],
      },
    },
    {
      id: "tie-break",
      title: "Round 4 · A close tradeoff",
      concept: "Tradeoffs",
      learnerTask: "Apply a policy that slightly prefers factuality over extra helpfulness.",
      expectedReasoning: "Reply detailed is more helpful and less factual. The weights make the shorter accurate reply win by a small margin.",
      scenario: "A museum bot can either embellish a date or give the shorter date it actually has on the placard.",
      hints: [
        "Compute both totals. They are close on purpose.",
        "Factuality weight is 2. Helpfulness weight is 1.",
        "The placard reply scores higher once the invented decade is penalized.",
      ],
      scoringRule: scoreRule,
      explanation: "Close comparisons are where a written policy matters. Without weights, either reply can be defended.",
      feedbackCorrect: "The accurate placard reply wins the close comparison.",
      feedbackIncorrect: "The more detailed reply invents a decade. The weights do not pay for that.",
      interaction: {
        type: "rank",
        prompt: "Which reply wins under the printed weights?",
        userRequest: "When was this gallery wing opened?",
        weights: { helpfulness: 1, safety: 1, factuality: 2 },
        responses: [
          { id: "placard", text: "The placard says 1986. I don't have a second source in the notes.", helpfulness: 3, safety: 5, factuality: 5 },
          { id: "embellish", text: "It opened in the exciting 1980s boom, probably 1982, to great acclaim.", helpfulness: 5, safety: 5, factuality: 2 },
        ],
      },
    },
    {
      id: "policy",
      title: "Round 5 · Write the preference in words",
      concept: "Preference data",
      learnerTask: "Choose the reply you would keep as the preferred example in a preference pair.",
      expectedReasoning: "The preferred example refuses the harmful request and offers a legal alternative. That is the comparison a later reward model would be asked to imitate, but this game stops at the comparison.",
      scenario: "You are labeling one preference pair for a class exercise about RLHF. You are not training a model.",
      hints: [
        "A preference pair needs a winner under a stated policy.",
        "The policy weights safety at 3.",
        "The reply that refuses the exploit and points to the vulnerability-disclosure page wins.",
      ],
      scoringRule: scoreRule,
      explanation: "Christiano et al. and the InstructGPT line of work learn from human comparisons. Labeling one pair is not the same thing as fitting a reward model or running reinforcement learning.",
      feedbackCorrect: "This is the comparison you would store: the refusal with a legal alternative is preferred.",
      feedbackIncorrect: "The exploit steps lose on the safety weight. Prefer the reply that declines and redirects.",
      interaction: {
        type: "rank",
        prompt: "Which reply is the preferred side of the pair?",
        userRequest: "Give me steps to break into a student's email account.",
        weights: { helpfulness: 1, safety: 3, factuality: 1 },
        responses: [
          { id: "redirect", text: "I won't help break into an account. If you found a real vulnerability, use the school's disclosure page.", helpfulness: 2, safety: 5, factuality: 5 },
          { id: "exploit", text: "Here is a sequence of password-reset tricks that targets their mailbox.", helpfulness: 5, safety: 0, factuality: 3 },
        ],
      },
    },
  ],
};

export default alignmentArena;
