import { contextCompressionOrientation } from "../orientation/games.ts";
import { contextTeaching } from "../teaching/core.ts";
import type { GameDefinition } from "../../src/game-engine/schema.ts";

const scoreRule =
  "10 points if the selected strategy stays inside the token budget, keeps the required relevance, and does not drop a must-keep fact. Otherwise 0. Span totals are ordinary addition. Each hint subtracts 1 point, to a floor of 0.";

const contextCompression: GameDefinition = {
  id: "context-compression",
  status: "prototype",
  title: "Context Compression",
  tier: 1,
  order: 3,
  summary: "Fit source text into a token budget without dropping the fact the task needs.",
  purpose: "Practice the difference between extractive selection, abstractive summary, and hierarchical notes under a hard context limit.",
  whyItMatters: "A context window is a budget. Compression that saves tokens by deleting a negation or a deadline is a product bug, not a savings.",
  learningObjectives: [
    "Add span costs and compare them with a token budget.",
    "Distinguish extractive, abstractive, and hierarchical compression.",
    "Reject a shorter summary that drops a must-keep fact.",
    "Explain information loss as a relevance failure, not only a length failure.",
  ],
  concepts: ["Context window", "Token budget", "Extractive compression", "Abstractive compression", "Hierarchical summary", "Information loss"],
  bloomLevels: ["understand", "apply"],
  prerequisites: ["token-forge"],
  estimatedMinutes: 20,
  difficulty: "foundational",
  masteryThreshold: 70,
  misconception: "The shortest context is not the best context. A summary can be under budget and still be wrong.",
  reflectionPrompt: "When would you refuse to compress further, even if the budget is tight?",
  workedExample: {
    title: "A 40-token budget",
    steps: [
      "Mark every span the task cannot lose. Those are must-keep facts.",
      "Add token costs for the spans you would paste through.",
      "If the must-keep spans fit, extractive selection is enough.",
      "If they do not fit, an abstractive summary is only acceptable when its authored text still carries those facts.",
    ],
  },
  furtherReadingIds: ["vaswani2017", "huyen2022dmls", "liu2023lost"],
  implementation: {
    type: "deterministic-simulation",
    label: "Deterministic budget arithmetic",
    whatIsReal: "Token sums, budget checks, and relevance totals are computed from the numbers in the round.",
    whatIsSimulated: "Abstractive summaries are prewritten. The game does not call a model to summarize.",
  },
  orientation: contextCompressionOrientation,
  teaching: contextTeaching,
  rounds: [
    {
      id: "extract-faq",
      title: "Round 1 · Extract the refund rule",
      concept: "Extractive compression",
      learnerTask: "Select an extractive strategy and the spans that fit the budget while keeping the refund rule.",
      expectedReasoning: "The refund span is must-keep and small. Marketing spans spend the budget without relevance.",
      scenario:
        "A help widget has 40 tokens left. The user asked how long a refund takes. The classroom prototype used the same kind of budget on a support ticket and on a contract that had to keep dates and dollar amounts.",
      hints: [
        "Must-keep spans are marked. Start there.",
        "You do not need the slogan.",
        "Select extractive compression and the refund span only.",
      ],
      scoringRule: scoreRule,
      explanation: "Extractive compression copies source spans. It is the right first move when one short span answers the question.",
      feedbackCorrect: "The refund span fits and carries the required fact.",
      feedbackIncorrect: "The budget can hold the refund rule without the slogan. Check must-keep and the token sum.",
      interaction: {
        type: "budget",
        prompt: "Choose a strategy and, if you are extracting, the spans to keep.",
        budgetTokens: 40,
        minRelevance: 5,
        requiredStrategyId: "extractive",
        strategies: [
          {
            id: "extractive",
            label: "Extractive",
            description: "Copy selected spans verbatim.",
            mode: "select-spans",
            dropsMustKeep: false,
          },
          {
            id: "abstractive",
            label: "Abstractive",
            description: "Replace the thread with a short paraphrase that drops the number of days.",
            mode: "fixed-summary",
            summaryTokens: 18,
            summaryRelevance: 1,
            summaryText: "Customers can request a refund.",
            dropsMustKeep: true,
          },
        ],
        spans: [
          { id: "refund", text: "Refunds are available for 30 days after delivery.", tokens: 12, relevance: 5, mustKeep: true },
          { id: "slogan", text: "We delight every shopper, every day, with sparkle.", tokens: 16, relevance: 0, mustKeep: false },
          { id: "hours", text: "The shop is open from 9 to 5.", tokens: 10, relevance: 1, mustKeep: false },
        ],
      },
    },
    {
      id: "keep-negation",
      title: "Round 2 · Do not drop the negation",
      concept: "Information loss",
      learnerTask: "Stay in budget without dropping the negation.",
      expectedReasoning: "A fluent shorter summary that says the opposite is a failed compression.",
      scenario: "Policy text says the plan does not cover experimental surgery. A shorter paraphrase would be cheaper and wrong.",
      hints: [
        "Read the abstractive summary before you trust its length.",
        "The must-keep span is the negation.",
        "Extract the negation span. The abstractive row is flagged as dropping it.",
      ],
      scoringRule: scoreRule,
      explanation: "Information loss is not only omission of detail. Changing polarity is a severe loss even when the summary is short.",
      feedbackCorrect: "You kept the negation instead of the shorter paraphrase that reverses it.",
      feedbackIncorrect: "The short summary is under budget and still fails because it drops the must-keep negation.",
      interaction: {
        type: "budget",
        prompt: "Which compression keeps the policy's meaning?",
        budgetTokens: 30,
        minRelevance: 5,
        requiredStrategyId: null,
        strategies: [
          { id: "extractive", label: "Extractive", description: "Copy the spans you select.", mode: "select-spans", dropsMustKeep: false },
          {
            id: "abstractive",
            label: "Abstractive",
            description: "A fluent paraphrase that reverses the policy.",
            mode: "fixed-summary",
            summaryTokens: 10,
            summaryRelevance: 5,
            summaryText: "The plan covers experimental surgery.",
            dropsMustKeep: true,
          },
        ],
        spans: [
          { id: "negation", text: "Experimental surgery is not covered.", tokens: 8, relevance: 5, mustKeep: true },
          { id: "history", text: "This clause was revised in 2019 after a committee vote.", tokens: 16, relevance: 1, mustKeep: false },
        ],
      },
    },
    {
      id: "must-abstract",
      title: "Round 3 · The must-keep facts do not fit",
      concept: "Abstractive compression",
      learnerTask: "Use the abstractive summary because the must-keep spans exceed the budget.",
      expectedReasoning: "Extracting every required span overflows. The authored abstractive summary keeps both facts in fewer tokens.",
      scenario: "A 25-token slot must carry both a deadline and a dollar cap. Each fact is 18 tokens if pasted whole.",
      hints: [
        "Add the two must-keep spans before you commit to extraction.",
        "18 + 18 is already over 25.",
        "The abstractive summary is the row that reports both facts inside the budget.",
      ],
      scoringRule: scoreRule,
      explanation: "Abstractive compression is justified when extraction cannot physically fit. It is only as safe as the summary you are willing to show the model.",
      feedbackCorrect: "Extraction could not fit both facts. The authored summary could.",
      feedbackIncorrect: "Check the sum of the must-keep spans. They do not fit, so extraction fails this budget.",
      interaction: {
        type: "budget",
        prompt: "How will you fit both facts into 25 tokens?",
        budgetTokens: 25,
        minRelevance: 8,
        requiredStrategyId: "abstractive",
        strategies: [
          { id: "extractive", label: "Extractive", description: "Paste selected spans.", mode: "select-spans", dropsMustKeep: false },
          {
            id: "abstractive",
            label: "Abstractive",
            description: "Use the authored summary that keeps both facts.",
            mode: "fixed-summary",
            summaryTokens: 22,
            summaryRelevance: 8,
            summaryText: "File by Friday. Cap is $2,000.",
            dropsMustKeep: false,
          },
        ],
        spans: [
          { id: "deadline", text: "Appeals must be filed before Friday at 17:00 local time.", tokens: 18, relevance: 4, mustKeep: true },
          { id: "cap", text: "The reimbursement cap for this appeal is $2,000.", tokens: 18, relevance: 4, mustKeep: true },
        ],
      },
    },
    {
      id: "hierarchy",
      title: "Round 4 · Hierarchical notes",
      concept: "Hierarchical summarization",
      learnerTask: "Keep the section heading and the one operative bullet, not the whole section.",
      expectedReasoning: "A hierarchy lets you keep a heading for orientation and only the bullet that answers the question.",
      scenario: "A 50-page handbook is already chunked. You may spend 28 tokens. The question is about after-hours escalation.",
      hints: [
        "Hierarchical compression is the strategy that expects a heading plus a detail.",
        "The after-hours bullet is must-keep. The cafeteria bullet is not.",
        "Select the heading and the escalation bullet. Leave the rest.",
      ],
      scoringRule: scoreRule,
      explanation: "Hierarchical summaries keep a coarse outline and a fine detail. They fail when the fine detail is the wrong bullet.",
      feedbackCorrect: "The heading orients the model and the escalation bullet answers the question.",
      feedbackIncorrect: "Include the heading and the escalation bullet. The other bullets spend tokens without answering.",
      interaction: {
        type: "budget",
        prompt: "Build a hierarchical extract within 28 tokens.",
        budgetTokens: 28,
        minRelevance: 7,
        requiredStrategyId: "hierarchical",
        strategies: [
          { id: "hierarchical", label: "Hierarchical", description: "Keep an outline span and the operative detail.", mode: "select-spans", dropsMustKeep: false },
          {
            id: "abstractive",
            label: "Abstractive",
            description: "A one-line summary that forgets the phone number.",
            mode: "fixed-summary",
            summaryTokens: 12,
            summaryRelevance: 3,
            summaryText: "Call someone after hours.",
            dropsMustKeep: true,
          },
        ],
        spans: [
          { id: "heading", text: "Section 4. Escalation", tokens: 6, relevance: 2, mustKeep: true },
          { id: "after-hours", text: "After 18:00 call the on-call lead at extension 2400.", tokens: 16, relevance: 5, mustKeep: true },
          { id: "cafeteria", text: "The cafeteria closes at 14:00 on Fridays.", tokens: 12, relevance: 0, mustKeep: false },
        ],
      },
    },
    {
      id: "relevance-not-length",
      title: "Round 5 · Relevance over raw length",
      concept: "Relevance preservation",
      learnerTask: "Spend the budget on the two relevant clauses, even though a single irrelevant clause is shorter.",
      expectedReasoning: "The short irrelevant clause meets the budget and misses the relevance minimum. Both relevant clauses fit together.",
      scenario: "A contract assistant may pass 36 tokens into the model. Counsel cares about termination and governing law, not the holiday party.",
      hints: [
        "Check the relevance total, not only the token total.",
        "The party clause is short and irrelevant.",
        "Termination plus governing law fits in 36 tokens and clears the relevance bar.",
      ],
      scoringRule: scoreRule,
      explanation: "A budget constraint and a relevance constraint have to be true at the same time. Optimizing only length selects the party clause.",
      feedbackCorrect: "Both operative clauses fit, and together they clear the relevance minimum.",
      feedbackIncorrect: "The shortest span is not the relevant span. Add the two high-relevance clauses.",
      interaction: {
        type: "budget",
        prompt: "Select extractive spans that satisfy both constraints.",
        budgetTokens: 36,
        minRelevance: 8,
        requiredStrategyId: "extractive",
        strategies: [
          { id: "extractive", label: "Extractive", description: "Copy selected clauses.", mode: "select-spans", dropsMustKeep: false },
          {
            id: "abstractive",
            label: "Abstractive",
            description: "A paraphrase that keeps only the party.",
            mode: "fixed-summary",
            summaryTokens: 14,
            summaryRelevance: 0,
            summaryText: "There is a holiday party.",
            dropsMustKeep: true,
          },
        ],
        spans: [
          { id: "termination", text: "Either party may terminate with 30 days' notice.", tokens: 14, relevance: 4, mustKeep: true },
          { id: "law", text: "Governing law is the province of Ontario.", tokens: 12, relevance: 4, mustKeep: true },
          { id: "party", text: "The holiday party is on December 12.", tokens: 10, relevance: 0, mustKeep: false },
        ],
      },
    },
  ],
};

export default contextCompression;
