import { gradientPlaygroundOrientation } from "../orientation/games.ts";
import type { GameDefinition } from "../../src/game-engine/schema.ts";

const scoreRule =
  "10 points if the educational loss model meets every target: validation loss, generalization gap, stability, forgetting, and method when a method is required. Otherwise 0. The curves are not neural-network training. Each hint subtracts 1 point, to a floor of 0.";

const sharedScenario = {
  baseLoss: 2,
  lrStableMax: 0.001,
  overfitEpoch: 5,
  loraFloor: 0.4,
  fullFloor: 0.18,
  forgettingEpoch: 4 as number | null,
};

const gradientPlayground: GameDefinition = {
  id: "gradient-playground",
  status: "prototype",
  title: "Gradient Playground",
  tier: 1,
  order: 5,
  summary: "Tune learning rate, epochs, batch size, and full fine-tuning versus LoRA on an educational loss model.",
  purpose: "Connect hyperparameters to training loss, validation loss, overfitting, and catastrophic forgetting without pretending to train a model.",
  whyItMatters: "Fine-tuning choices are visible in the gap between training and validation, and in whether earlier skills survive.",
  learningObjectives: [
    "Recognize a divergent learning rate on the educational curve.",
    "Separate training loss from validation loss.",
    "Choose LoRA when the scenario penalizes full fine-tuning for forgetting.",
    "Choose full fine-tuning when the loss floor of LoRA cannot meet the target.",
  ],
  concepts: ["Learning rate", "Epochs", "Batch size", "Training loss", "Validation loss", "Full fine-tuning", "LoRA", "Overfitting", "Catastrophic forgetting"],
  bloomLevels: ["understand", "apply", "analyze"],
  prerequisites: ["attention-architect"],
  estimatedMinutes: 25,
  difficulty: "intermediate",
  masteryThreshold: 70,
  misconception: "A lower training loss is not by itself a successful fine-tune, and these curves are not evidence that a real model was trained.",
  reflectionPrompt: "Which target would you refuse to relax in a real fine-tune: validation loss, or preservation of the prior task? Why?",
  workedExample: {
    title: "Reading the educational model",
    steps: [
      "If the learning rate is above the scenario's stable maximum, the curves climb. That is the divergence rule.",
      "Training loss falls toward a floor. LoRA's floor is higher because the exercise gives it less capacity.",
      "After the overfitting epoch, the validation gap grows faster for full fine-tuning than for LoRA.",
      "On and after the forgetting epoch, full fine-tuning adds a penalty. LoRA does not, in this model.",
    ],
  },
  furtherReadingIds: ["hu2021lora", "huyen2022dmls"],
  implementation: {
    type: "educational-simulation",
    label: "Educational loss curves",
    whatIsReal: "The plotted numbers are computed from the formula documented in the concept guide and in src/game-engine/models/loss-curve.ts.",
    whatIsSimulated: "Nothing is trained. There are no gradients, parameters, or datasets behind the curves.",
  },
  orientation: gradientPlaygroundOrientation,
  rounds: [
    {
      id: "stabilize",
      title: "Round 1 · Stop the divergence",
      concept: "Learning rate",
      learnerTask: "Bring the run into the stable region and under the validation target. Either method is allowed.",
      expectedReasoning: "The initial learning rate is above the stable maximum, so the curve climbs until the rate comes down.",
      scenario: "A classmate doubled the learning rate and the validation curve exploded. Recover a stable run under 0.8 validation loss.",
      hints: [
        "Divergence in this model is a learning-rate comparison, not a mystery.",
        "The stable maximum for this scenario is 0.001.",
        "Try a learning rate of 0.0004 or 0.0005 and at least 4 epochs.",
      ],
      scoringRule: scoreRule,
      explanation: "The model marks learning rates above lrStableMax as divergent and makes the curves climb. That is a teaching rule, not an optimizer diagnostic from a real run.",
      feedbackCorrect: "The learning rate is inside the stable band and validation loss is under the cap.",
      feedbackIncorrect: "Lower the learning rate until the status is no longer diverging, then give it enough epochs to fall.",
      interaction: {
        type: "curve",
        prompt: "Adjust the controls until every target reads as met.",
        scenario: { ...sharedScenario, forgettingEpoch: null },
        targets: { maxFinalValLoss: 0.8, maxGap: 0.5, forbidDivergence: true, forbidForgetting: false, requiredMethod: null },
        initial: { learningRate: 0.002, epochs: 3, batchSize: 16, method: "full" },
        lrMin: 0.0001,
        lrMax: 0.003,
        epochMin: 1,
        epochMax: 12,
      },
    },
    {
      id: "gap",
      title: "Round 2 · Close the gap",
      concept: "Overfitting",
      learnerTask: "Finish with a generalization gap of at most 0.15 and validation loss at most 0.7.",
      expectedReasoning: "A long full fine-tune past the overfitting epoch opens a gap. Fewer epochs or LoRA keeps the gap smaller.",
      scenario: "Training loss looks excellent and validation loss has drifted. The review will reject a gap above 0.15.",
      hints: [
        "The gap is validation loss minus training loss at the final epoch.",
        "Full fine-tuning grows that gap faster after epoch 5.",
        "Stop earlier, or switch to LoRA, before the gap crosses 0.15.",
      ],
      scoringRule: scoreRule,
      explanation: "Overfitting in this exercise is a scheduled gap, not a measured dataset effect. The shape is what a learner should recognize: training improves while validation does not.",
      feedbackCorrect: "The final gap is inside the review limit.",
      feedbackIncorrect: "The run is stable but the gap is too wide. Shorten the full fine-tune or use LoRA.",
      interaction: {
        type: "curve",
        prompt: "Meet the validation and gap limits.",
        scenario: { ...sharedScenario, forgettingEpoch: null },
        targets: { maxFinalValLoss: 0.7, maxGap: 0.15, forbidDivergence: true, forbidForgetting: false, requiredMethod: null },
        initial: { learningRate: 0.0008, epochs: 12, batchSize: 32, method: "full" },
        lrMin: 0.0001,
        lrMax: 0.003,
        epochMin: 1,
        epochMax: 12,
      },
    },
    {
      id: "lora-forget",
      title: "Round 3 · Keep the prior task",
      concept: "Catastrophic forgetting",
      learnerTask: "Use LoRA. Full fine-tuning is marked as forgetting once it runs long enough to fit.",
      expectedReasoning: "The forgetting epoch is 4, so a full fine-tune that actually fits also enters the penalty. LoRA reaches a usable floor without that penalty.",
      scenario: "The adapter must learn a small support style and still pass last semester's skill check. Full fine-tuning fails that check in this scenario.",
      hints: [
        "Read the method target, not only the training loss.",
        "Full fine-tuning can show a lower training loss and still fail forgetting.",
        "Select LoRA, a learning rate around 0.0004, and about 4 to 6 epochs.",
      ],
      scoringRule: scoreRule,
      explanation: "Catastrophic forgetting is represented here as a penalty applied only to full fine-tuning after a configured epoch. A real retention eval would measure the old task directly.",
      feedbackCorrect: "LoRA meets the loss cap without entering the forgetting penalty.",
      feedbackIncorrect: "Full fine-tuning is disallowed by the forgetting target in this scenario, even if its training loss is lower.",
      interaction: {
        type: "curve",
        prompt: "Satisfy the loss cap without the forgetting penalty.",
        scenario: sharedScenario,
        targets: { maxFinalValLoss: 0.55, maxGap: 0.2, forbidDivergence: true, forbidForgetting: true, requiredMethod: "lora" },
        initial: { learningRate: 0.0008, epochs: 8, batchSize: 16, method: "full" },
        lrMin: 0.0001,
        lrMax: 0.003,
        epochMin: 1,
        epochMax: 12,
      },
    },
    {
      id: "need-capacity",
      title: "Round 4 · When LoRA's floor is too high",
      concept: "Parameter-efficient versus full fine-tuning",
      learnerTask: "Use full fine-tuning because LoRA cannot reach the required validation loss.",
      expectedReasoning: "LoRA's floor is 0.7 and the target is 0.35. Only full fine-tuning's lower floor can qualify, and forgetting is turned off in this scenario.",
      scenario: "A domain corpus is large enough that the team accepted a full fine-tune. The acceptance test requires validation loss at or below 0.35. There is no prior-task constraint in this round.",
      hints: [
        "Look at the two floors described in the worked example.",
        "LoRA cannot go below its floor no matter how many epochs you add.",
        "Use full fine-tuning, keep the learning rate stable, and stop before the gap grows.",
      ],
      scoringRule: scoreRule,
      explanation: "LoRA trains a small update. This model gives it a higher loss floor to represent limited capacity. That floor is a teaching parameter, not a measured rank.",
      feedbackCorrect: "Full fine-tuning is what gets under the floor LoRA cannot cross in this scenario.",
      feedbackIncorrect: "LoRA's floor is above the target. Switch method, and watch the gap if you train too long.",
      interaction: {
        type: "curve",
        prompt: "Reach a validation loss the low-capacity method cannot reach.",
        scenario: { baseLoss: 2, lrStableMax: 0.001, overfitEpoch: 8, loraFloor: 0.7, fullFloor: 0.18, forgettingEpoch: null },
        targets: { maxFinalValLoss: 0.35, maxGap: 0.2, forbidDivergence: true, forbidForgetting: false, requiredMethod: "full" },
        initial: { learningRate: 0.0004, epochs: 6, batchSize: 32, method: "lora" },
        lrMin: 0.0001,
        lrMax: 0.003,
        epochMin: 1,
        epochMax: 12,
      },
    },
    {
      id: "batch-noise",
      title: "Round 5 · Batch size and a tight gap",
      concept: "Batch size",
      learnerTask: "Meet a tight validation target with LoRA. A tiny batch adds noise that can push you over the cap.",
      expectedReasoning: "The educational noise term shrinks as batch size grows. Combined with a stable rate and a short LoRA run, batch 32 clears the cap.",
      scenario: "The lab GPU fits either a batch of 8 or a batch of 32. The cap is tight, so the noisier curve fails.",
      hints: [
        "Batch size in this model changes a noise term, not throughput.",
        "A batch of 8 adds more noise than a batch of 32.",
        "Use LoRA, learning rate 0.0005, 4 epochs, and batch 32.",
      ],
      scoringRule: scoreRule,
      explanation: "Real batches also change gradient variance and speed. Here, batch size only scales a documented noise term so the effect is visible.",
      feedbackCorrect: "The larger batch keeps the educational noise inside the cap.",
      feedbackIncorrect: "Increase the batch and stay with a short, stable LoRA run.",
      interaction: {
        type: "curve",
        prompt: "Clear the tight validation cap.",
        scenario: { baseLoss: 1.2, lrStableMax: 0.001, overfitEpoch: 6, loraFloor: 0.3, fullFloor: 0.16, forgettingEpoch: 3 },
        targets: { maxFinalValLoss: 0.32, maxGap: 0.12, forbidDivergence: true, forbidForgetting: true, requiredMethod: "lora" },
        initial: { learningRate: 0.0005, epochs: 4, batchSize: 8, method: "lora" },
        lrMin: 0.0001,
        lrMax: 0.003,
        epochMin: 1,
        epochMax: 12,
      },
    },
  ],
};

export default gradientPlayground;
