import type { GameDefinition } from "../../src/game-engine/schema.ts";

const scoreRule =
  "10 points if precision and recall of the top-k list meet the round's minimums. Keyword score is the fraction of query keywords found in the chunk. Vector score is cosine similarity clamped at 0. Hybrid is the average of those two. Each hint subtracts 1 point, to a floor of 0.";

const retrievalLab: GameDefinition = {
  id: "retrieval-lab",
  status: "prototype",
  title: "Retrieval Lab",
  tier: 2,
  order: 10,
  summary: "Compare keyword, vector, and hybrid retrieval on a tiny local corpus, including a metadata filter.",
  purpose: "Make chunking, embeddings, ranking, precision, recall, and grounding concrete on data the learner can inspect.",
  whyItMatters: "A retrieval-augmented system answers from what it retrieves. A confident answer over the wrong chunk is a grounding failure.",
  learningObjectives: [
    "Contrast keyword overlap with cosine similarity on toy vectors.",
    "Compute precision and recall for a top-k list.",
    "Use a metadata filter when two chunks share words and only one is in scope.",
    "Choose hybrid retrieval when each single method ranks a distractor first.",
  ],
  concepts: ["RAG", "Chunking", "Embeddings", "Vector search", "Keyword search", "Hybrid retrieval", "Metadata filtering", "Reranking", "Precision", "Recall", "Grounding"],
  bloomLevels: ["apply", "analyze", "evaluate"],
  prerequisites: [],
  estimatedMinutes: 30,
  difficulty: "advanced",
  masteryThreshold: 70,
  misconception: "The nearest vector is not automatically the chunk that answers the question, and a retrieved chunk is not evidence unless the answer stays inside it.",
  reflectionPrompt: "What would you log so a later reviewer could see which chunk grounded an answer?",
  workedExample: {
    title: "Precision and recall for one query",
    steps: [
      "Mark which chunks actually answer the query. That set is the relevant set.",
      "Rank the corpus with the selected method and take top-k.",
      "Precision is relevant retrieved divided by retrieved. Recall is relevant retrieved divided by relevant total.",
      "If a filter removes the only relevant chunk, recall falls even when the remaining list looks clean.",
    ],
  },
  furtherReadingIds: ["lewis2020rag", "karpukhin2020dpr", "reimers2019sbert"],
  implementation: {
    type: "simplified-computation",
    label: "Local retrieval over toy vectors",
    whatIsReal: "Cosine similarity, keyword overlap, hybrid scores, precision, and recall are computed in the browser.",
    whatIsSimulated: "The vectors are 3-dimensional teaching examples, not the output of an embedding model. There is no reranker model; top-k on the score is the only ranker.",
  },
  rounds: [
    {
      id: "lexical",
      title: "Round 1 · The nearest vector is the wrong policy",
      concept: "Keyword versus vector",
      learnerTask: "Retrieve the refund rule. Pure vector search prefers a distractor.",
      expectedReasoning: "The distractor sits on the query vector and does not contain the words refund and window. Keyword or hybrid puts the policy chunk first.",
      scenario: "A support bot may pass one chunk into the answer. The user asked for the refund window.",
      hints: [
        "Read the top hit before you trust the method name.",
        "The price-match chunk is close in the toy vector space and irrelevant.",
        "Switch from vector to keyword or hybrid. Top-1 should be the refund policy.",
      ],
      scoringRule: scoreRule,
      explanation: "Dense retrieval can prefer a semantic neighbor that does not contain the operative fact. This corpus makes that failure obvious because the vectors are visible.",
      feedbackCorrect: "The refund policy is the top hit, so both precision and recall are 1 at k=1.",
      feedbackIncorrect: "Vector search is ranking the price-match chunk first. Change method.",
      interaction: {
        type: "retrieval",
        prompt: "Choose a method. A filter is not available on this corpus.",
        query: "What is the refund window?",
        queryVector: [1, 0, 0],
        queryKeywords: ["refund", "window"],
        topK: 1,
        minRecall: 1,
        minPrecision: 1,
        initialMethod: "vector",
        filter: null,
        chunks: [
          { id: "policy", title: "Refund policy", text: "The refund window is 30 days after delivery.", vector: [0.2, 0.9, 0], keywords: ["refund", "window", "30"], metadata: { product: "widget" }, relevant: true },
          { id: "price", title: "Price match", text: "Price match applies within 14 days and is not a refund.", vector: [1, 0, 0], keywords: ["price", "match"], metadata: { product: "widget" }, relevant: false },
          { id: "ship", title: "Shipping", text: "Standard shipping takes five business days.", vector: [0, 0, 1], keywords: ["shipping"], metadata: { product: "widget" }, relevant: false },
        ],
      },
    },
    {
      id: "synonym",
      title: "Round 2 · The words do not match",
      concept: "Embeddings",
      learnerTask: "Retrieve the refund chunk for a query that says “money back” instead of “refund”.",
      expectedReasoning: "Keyword overlap is zero on the relevant chunk. The toy vector was placed near it, so vector or hybrid works.",
      scenario: "Customers do not use the policy's vocabulary. The only relevant chunk never contains the words money or back.",
      hints: [
        "Check whether the relevant chunk shares any query keyword.",
        "It does not. Keyword ranking has nothing lexical to hold onto.",
        "Use vector or hybrid so the nearby toy embedding can surface the refund chunk.",
      ],
      scoringRule: scoreRule,
      explanation: "This is the case dense passage retrieval is meant to help: paraphrases. The vector was authored to be near the query. A real embedding model might not place it there.",
      feedbackCorrect: "The paraphrase was retrieved by vector similarity rather than by shared words.",
      feedbackIncorrect: "Keyword search cannot see “refund” inside a query that never says it. Switch method.",
      interaction: {
        type: "retrieval",
        prompt: "Retrieve the chunk that answers a paraphrased question.",
        query: "How do I get my money back?",
        queryVector: [0.95, 0.1, 0],
        queryKeywords: ["money", "back"],
        topK: 1,
        minRecall: 1,
        minPrecision: 1,
        initialMethod: "keyword",
        filter: null,
        chunks: [
          { id: "a-register", title: "Cash drawer", text: "Registers are counted at closing.", vector: [0, 1, 0], keywords: ["drawer", "count"], metadata: { desk: "store" }, relevant: false },
          { id: "refund-policy", title: "Refund policy", text: "Refunds are issued to the original payment method within 30 days.", vector: [1, 0, 0], keywords: ["refund", "days"], metadata: { desk: "support" }, relevant: true },
        ],
      },
    },
    {
      id: "filter",
      title: "Round 3 · The right product",
      concept: "Metadata filtering",
      learnerTask: "Turn on the product filter so the gadget warranty cannot outrank the widget warranty.",
      expectedReasoning: "Both chunks talk about warranties. Only the widget chunk is in scope. The gadget chunk has the higher toy cosine, so unfiltered vector search fails.",
      scenario: "The catalog has two warranties. The user is holding a widget. Passing the gadget warranty would ground the answer in the wrong product.",
      hints: [
        "Read the product metadata, not only the title.",
        "Unfiltered search prefers the gadget chunk.",
        "Enable the widget filter. Keyword or vector will then only see the widget chunk.",
      ],
      scoringRule: scoreRule,
      explanation: "Metadata filters run before ranking in this lab. They are how a retrieval system enforces scope that the embedding was not trained to know.",
      feedbackCorrect: "The widget warranty is the only chunk left, and it is the relevant one.",
      feedbackIncorrect: "Without the filter, the gadget chunk wins on cosine. Turn the filter on.",
      interaction: {
        type: "retrieval",
        prompt: "Scope the search to widgets.",
        query: "What is the widget warranty?",
        queryVector: [1, 0, 0],
        queryKeywords: ["widget", "warranty"],
        topK: 1,
        minRecall: 1,
        minPrecision: 1,
        initialMethod: "vector",
        filter: { field: "product", value: "widget", label: "product is widget" },
        chunks: [
          { id: "gadget", title: "Gadget warranty", text: "Gadgets are covered for 90 days.", vector: [1, 0, 0], keywords: ["warranty", "gadget"], metadata: { product: "gadget" }, relevant: false },
          { id: "widget", title: "Widget warranty", text: "Widgets are covered for one year.", vector: [0.4, 0.8, 0], keywords: ["widget", "warranty", "year"], metadata: { product: "widget" }, relevant: true },
        ],
      },
    },
    {
      id: "hybrid",
      title: "Round 4 · Each single method is fooled",
      concept: "Hybrid retrieval",
      learnerTask: "Use hybrid scoring so the true chunk outranks both distractors.",
      expectedReasoning: "The vector distractor shares direction and no keywords. The keyword distractor shares words and almost no direction. The true chunk is second-best on each and first on the average.",
      scenario: "A policy question uses the word “cap” and is about a dollar limit. Another chunk uses “cap” for a baseball hat. A third chunk is a near vector about “limits” in a different policy.",
      hints: [
        "Look at the top hit for vector alone and for keyword alone.",
        "Each of those top hits is marked irrelevant.",
        "Hybrid averages the two scores. That is what promotes the dollar-cap chunk.",
      ],
      scoringRule: scoreRule,
      explanation: "Hybrid retrieval is a simple fusion. This lab averages two scores. Production systems often use a learned reranker after that fusion; this round does not.",
      feedbackCorrect: "The dollar-cap chunk is first only under the hybrid score.",
      feedbackIncorrect: "Stay on hybrid. Either single method is ranking a distractor first.",
      interaction: {
        type: "retrieval",
        prompt: "Pick the method whose top hit is the dollar cap.",
        query: "What is the reimbursement cap?",
        queryVector: [1, 0, 0],
        queryKeywords: ["reimbursement", "cap"],
        topK: 1,
        minRecall: 1,
        minPrecision: 1,
        initialMethod: "vector",
        filter: null,
        chunks: [
          { id: "vector-bait", title: "Spending limit memo", text: "Departments should limit discretionary spending.", vector: [1, 0, 0], keywords: ["limit"], metadata: { desk: "finance" }, relevant: false },
          { id: "keyword-bait", title: "Team caps", text: "Order baseball caps for the team by Friday.", vector: [0, 1, 0], keywords: ["cap", "reimbursement"], metadata: { desk: "events" }, relevant: false },
          { id: "dollar-cap", title: "Reimbursement cap", text: "The reimbursement cap is $2,000 per trip.", vector: [0.6, 0.2, 0], keywords: ["reimbursement"], metadata: { desk: "finance" }, relevant: true },
        ],
      },
    },
    {
      id: "recall",
      title: "Round 5 · Bring both clauses back",
      concept: "Recall",
      learnerTask: "Retrieve both relevant clauses. Top-2 with the wrong method drops one of them.",
      expectedReasoning: "Recall is about the relevant set, not about a single pleasing top hit. Hybrid with the filter keeps both Ontario clauses and drops the cafeteria note.",
      scenario: "Counsel needs both the termination clause and the governing-law clause. Either one alone is an incomplete ground for the answer.",
      hints: [
        "There are two relevant chunks. Top-2 must contain both.",
        "The cafeteria chunk is a lexical distractor if you search without the legal filter.",
        "Turn on the legal-desk filter and use hybrid or keyword. Vector without the filter ranks the cafeteria note too high.",
      ],
      scoringRule: scoreRule,
      explanation: "Grounding a two-fact answer requires recall of both facts. A pretty top-1 with recall 0.5 is a failed retrieval for this task.",
      feedbackCorrect: "Both clauses are in the top 2, so recall and precision meet the bar.",
      feedbackIncorrect: "One of the two legal clauses is missing from the list. Adjust method or filter.",
      interaction: {
        type: "retrieval",
        prompt: "Retrieve both legal clauses.",
        query: "termination and governing law",
        queryVector: [1, 0.2, 0],
        queryKeywords: ["termination", "governing", "law"],
        topK: 2,
        minRecall: 1,
        minPrecision: 1,
        initialMethod: "vector",
        filter: { field: "desk", value: "legal", label: "desk is legal" },
        chunks: [
          { id: "termination", title: "Termination", text: "Either party may terminate with 30 days' notice.", vector: [0.8, 0.2, 0], keywords: ["termination", "notice"], metadata: { desk: "legal" }, relevant: true },
          { id: "law", title: "Governing law", text: "Governing law is Ontario.", vector: [0.7, 0.5, 0], keywords: ["governing", "law", "ontario"], metadata: { desk: "legal" }, relevant: true },
          { id: "cafe", title: "Cafeteria", text: "The cafeteria closes early on Friday.", vector: [0.95, 0.05, 0], keywords: ["friday"], metadata: { desk: "ops" }, relevant: false },
        ],
      },
    },
  ],
};

export default retrievalLab;
