import { shipItOrientation } from "../orientation/games.ts";
import type { GameDefinition } from "../../src/game-engine/schema.ts";

const scoreRule =
  "10 points when every projected metric is inside its limit. Otherwise 0. Projections are baseline plus the sum of selected lever effects. Each hint subtracts 1 point, to a floor of 0.";

const shipIt: GameDefinition = {
  id: "ship-it-simulator",
  status: "prototype",
  title: "Ship-It Simulator",
  tier: 2,
  order: 8,
  summary: "Meet a latency, cost, and reliability target by combining serving levers.",
  purpose: "Practice production tradeoffs: caching, retries with backoff, fallbacks, smaller models, and replicas.",
  whyItMatters: "A serving change that fixes latency can break the error budget, and a retry policy can amplify an outage.",
  learningObjectives: [
    "Project latency, cost, and success rate from a baseline plus lever effects.",
    "Add retries with backoff when the error budget is the failing constraint.",
    "Avoid a lever that improves one metric by breaking another.",
    "State an SLO as a numeric limit rather than as a slogan.",
  ],
  concepts: ["Latency", "Throughput", "Retries", "Exponential backoff", "Caching", "Fallback models", "Rate limits", "Cost", "Availability", "SLO"],
  bloomLevels: ["apply", "analyze", "evaluate"],
  prerequisites: [],
  estimatedMinutes: 25,
  difficulty: "advanced",
  masteryThreshold: 70,
  misconception: "Retrying faster is not the same thing as backing off, and a cache does not fix an error budget by itself.",
  reflectionPrompt: "Which SLO would you page a human for, and which would you absorb with a fallback model?",
  workedExample: {
    title: "One projection",
    steps: [
      "Write down the baseline for each limit.",
      "Add the effect of each lever you turn on. Effects can be negative.",
      "A maximum limit passes when the projection is at or below it. A minimum limit passes when the projection is at or above it.",
      "If one lever fixes latency and breaks errors, it is not yet a solution.",
    ],
  },
  furtherReadingIds: ["huyen2022dmls", "bommasani2022foundation"],
  implementation: {
    type: "deterministic-simulation",
    label: "Parameterized serving simulation",
    whatIsReal: "The arithmetic from baseline and lever effects to projected metrics.",
    whatIsSimulated: "There is no cluster, queue, or live API. The effect sizes are authored for the scenario.",
  },
  orientation: shipItOrientation,
  rounds: [
    {
      id: "support-api",
      title: "Round 1 · A support API over budget",
      concept: "Combined levers",
      learnerTask: "Bring p95 under 250 ms, monthly cost under $8,000, and success to at least 99 percent.",
      expectedReasoning: "Cache and a smaller model buy latency and cost. Retries, a fallback, and a replica are what get reliability over the line without giving the latency back.",
      scenario: "The assistant API serves 10,000 requests a day. p95 is 500 ms, the month costs $10,000, and success is 96 percent. The SLO is p95 below 250 ms, cost at most $8,000, and success at least 99 percent.",
      hints: [
        "Batching makes p95 worse in this table. Leave it off.",
        "You need both a latency cut and a reliability boost.",
        "Turn on cache, smaller model, retry with backoff, fallback, and replica. Leave batching off.",
      ],
      scoringRule: scoreRule,
      explanation: "The numbers are a scenario, not a trace. The lesson is that the SLO is a set of inequalities, so a single clever lever is rarely enough.",
      feedbackCorrect: "Every projected metric is inside its limit.",
      feedbackIncorrect: "At least one limit is still broken. Read the row that says outside limit.",
      interaction: {
        type: "levers",
        prompt: "Select the serving levers.",
        baseline: { p95: 500, cost: 10000, success: 96 },
        metrics: [
          { id: "p95", label: "p95 latency", unit: " ms", direction: "max", limit: 250 },
          { id: "cost", label: "Monthly cost", unit: "", direction: "max", limit: 8000 },
          { id: "success", label: "Success rate", unit: "%", direction: "min", limit: 99 },
        ],
        levers: [
          { id: "cache", label: "Response cache", description: "Serve repeated questions from cache.", effects: { p95: -180, cost: -2200, success: 0.5 } },
          { id: "batching", label: "Aggressive batching", description: "Wait to fill a batch. Throughput rises, p95 gets worse.", effects: { p95: 40, cost: -800, success: 0 } },
          { id: "smaller", label: "Smaller model", description: "Route most calls to a cheaper model.", effects: { p95: -90, cost: -2000, success: -0.4 } },
          { id: "retry", label: "Retry with backoff", description: "Retry failed calls with exponential backoff and a cap.", effects: { p95: 25, cost: 300, success: 2.2 } },
          { id: "fallback", label: "Fallback model", description: "If the primary errors, answer from a smaller backup.", effects: { p95: 15, cost: 200, success: 1.6 } },
          { id: "replica", label: "Second region", description: "A warm replica absorbs a zone failure.", effects: { p95: -30, cost: 900, success: 0.6 } },
        ],
      },
    },
    {
      id: "retry-storm",
      title: "Round 2 · Do not stampede the dependency",
      concept: "Backoff versus tight retries",
      learnerTask: "Cut the error rate without tripling the request load.",
      expectedReasoning: "Tight retries multiply load. Capped backoff plus a cache reduces errors and load together.",
      scenario: "A downstream rate limit is already tripping. Tight retries would send three calls per user failure. Load must stay at or below 120 units and the error rate must be at or below 2 percent. Cost must stay at or below 90.",
      hints: [
        "The tight-retry lever increases load a lot.",
        "Backoff increases load only a little and cuts errors.",
        "Use cache and capped backoff. Leave tight retries off.",
      ],
      scoringRule: scoreRule,
      explanation: "Retries without a cap and without backoff turn a short dependency failure into a self-inflicted outage. The load number here stands in for requests per second.",
      feedbackCorrect: "Errors fell without a retry storm.",
      feedbackIncorrect: "Tight retries blow the load budget. Use capped backoff instead.",
      interaction: {
        type: "levers",
        prompt: "Choose a retry policy that the dependency can survive.",
        baseline: { load: 100, errors: 8, cost: 70 },
        metrics: [
          { id: "load", label: "Load", unit: "", direction: "max", limit: 120 },
          { id: "errors", label: "Error rate", unit: "%", direction: "max", limit: 2 },
          { id: "cost", label: "Cost index", unit: "", direction: "max", limit: 90 },
        ],
        levers: [
          { id: "tight", label: "Immediate retries", description: "Retry twice with no delay.", effects: { load: 80, errors: -5, cost: 20 } },
          { id: "backoff", label: "Capped backoff", description: "Three attempts, exponential delay, then stop.", effects: { load: 15, errors: -6, cost: 8 } },
          { id: "cache", label: "Cache safe GETs", description: "Don't repeat identical reads.", effects: { load: -30, errors: -1, cost: -10 } },
        ],
      },
    },
    {
      id: "rate-limit",
      title: "Round 3 · Stay under a rate limit",
      concept: "Rate limits",
      learnerTask: "Keep outbound calls at or below 50 per second while holding p95 at or below 300 ms and success at or above 98 percent.",
      expectedReasoning: "A queue smooths bursts. A cache removes calls. Raising the client concurrency breaks the provider's rate limit.",
      scenario: "The model provider allows 50 requests per second. The current client bursts to 80 and then times out.",
      hints: [
        "More concurrency is the trap.",
        "You need fewer calls and a place for the burst to wait.",
        "Enable the queue and the cache. Leave extra concurrency off.",
      ],
      scoringRule: scoreRule,
      explanation: "A rate limit is a hard upstream constraint. Client concurrency does not create more quota.",
      feedbackCorrect: "The projection respects the provider quota and the latency SLO.",
      feedbackIncorrect: "Extra concurrency pushes calls per second over the provider limit.",
      interaction: {
        type: "levers",
        prompt: "Shape traffic to the quota.",
        baseline: { qps: 80, p95: 280, success: 94 },
        metrics: [
          { id: "qps", label: "Calls per second", unit: "", direction: "max", limit: 50 },
          { id: "p95", label: "p95 latency", unit: " ms", direction: "max", limit: 300 },
          { id: "success", label: "Success", unit: "%", direction: "min", limit: 98 },
        ],
        levers: [
          { id: "queue", label: "Admission queue", description: "Hold bursts instead of sending them.", effects: { qps: -25, p95: 20, success: 3 } },
          { id: "cache", label: "Cache", description: "Drop duplicate calls.", effects: { qps: -20, p95: -40, success: 1 } },
          { id: "concurrency", label: "Double concurrency", description: "Open more in-flight client calls.", effects: { qps: 30, p95: -10, success: -4 } },
        ],
      },
    },
    {
      id: "fallback-quality",
      title: "Round 4 · A fallback that is allowed to be shorter",
      concept: "Fallback models",
      learnerTask: "Hit the latency SLO without dropping answer acceptance below 90 percent.",
      expectedReasoning: "The tiny model is fast and unacceptable. The mid-size fallback is fast enough and stays above the quality floor. The giant model misses latency.",
      scenario: "Interactive grading must answer in 400 ms at p95. Faculty will reject a fallback that drops acceptance below 90 percent. Cost must stay at or below 60.",
      hints: [
        "Read the acceptance column, not only latency.",
        "The tiny model fails acceptance.",
        "Select the mid-size fallback and the cache.",
      ],
      scoringRule: scoreRule,
      explanation: "A fallback is a product decision about which failures are acceptable. Latency alone does not choose it.",
      feedbackCorrect: "The mid-size fallback clears latency and acceptance together.",
      feedbackIncorrect: "The fastest model fails the acceptance floor. Check that column.",
      interaction: {
        type: "levers",
        prompt: "Choose the fallback posture.",
        baseline: { p95: 700, acceptance: 96, cost: 80 },
        metrics: [
          { id: "p95", label: "p95 latency", unit: " ms", direction: "max", limit: 400 },
          { id: "acceptance", label: "Acceptance", unit: "%", direction: "min", limit: 90 },
          { id: "cost", label: "Cost index", unit: "", direction: "max", limit: 60 },
        ],
        levers: [
          { id: "tiny", label: "Tiny fallback", description: "Very fast, often incomplete.", effects: { p95: -500, acceptance: -20, cost: -40 } },
          { id: "mid", label: "Mid-size fallback", description: "Fast enough, still specific.", effects: { p95: -280, acceptance: -4, cost: -15 } },
          { id: "cache", label: "Cache repeated rubrics", description: "Repeated prompts skip the model.", effects: { p95: -40, acceptance: 0, cost: -10 } },
        ],
      },
    },
    {
      id: "slo-page",
      title: "Round 5 · Availability versus a page",
      concept: "Service-level objectives",
      learnerTask: "Reach 99.5 percent success without pushing p95 over 200 ms or cost over 100.",
      expectedReasoning: "A human on-call page fixes the hardest failures but is expensive and slow. Cache plus failover plus a capped retry meets the SLO without paging on every error.",
      scenario: "The on-call rotation is two people. Paging them for every timeout will burn the team. The SLO is still 99.5 percent success.",
      hints: [
        "Paging works numerically and breaks the cost and latency limits.",
        "You can reach 99.5 without the page.",
        "Enable cache, failover, and capped retry. Leave the page off.",
      ],
      scoringRule: scoreRule,
      explanation: "An SLO does not require a human in the loop for every miss. It requires a designed way to absorb the miss.",
      feedbackCorrect: "The SLO is met without paging a human for ordinary timeouts.",
      feedbackIncorrect: "The page lever is the expensive one. There is a combination that avoids it.",
      interaction: {
        type: "levers",
        prompt: "Meet the SLO.",
        baseline: { success: 97, p95: 180, cost: 70 },
        metrics: [
          { id: "success", label: "Success", unit: "%", direction: "min", limit: 99.5 },
          { id: "p95", label: "p95 latency", unit: " ms", direction: "max", limit: 200 },
          { id: "cost", label: "Cost index", unit: "", direction: "max", limit: 100 },
        ],
        levers: [
          { id: "page", label: "Page a human", description: "A person finishes the request.", effects: { success: 2.8, p95: 80, cost: 50 } },
          { id: "cache", label: "Cache", description: "Remove repeat load.", effects: { success: 0.4, p95: -20, cost: -8 } },
          { id: "failover", label: "Failover region", description: "Shift traffic when the primary errors.", effects: { success: 1.4, p95: 10, cost: 12 } },
          { id: "retry", label: "Capped retry", description: "One retry with backoff.", effects: { success: 0.8, p95: 15, cost: 6 } },
        ],
      },
    },
  ],
};

export default shipIt;
