import type { GameDefinition } from "../../src/game-engine/schema.ts";

const scoreRule =
  "10 points if the selected blocks cover every required concern, stay within the relative cost and latency budgets, and do not include a conflicting pair. Otherwise 0. Each hint subtracts 1 point, to a floor of 0.";

const systemComposer: GameDefinition = {
  id: "system-composer",
  status: "prototype",
  title: "System Composer",
  tier: 2,
  order: 11,
  summary: "Assemble a small LLM system that covers grounding, safety, latency, and operations together.",
  purpose: "Move from isolated techniques to a system that names which block is responsible for which constraint.",
  whyItMatters: "A model call by itself does not ground, refuse, cache, or explain a production failure. Those are separate parts of the architecture.",
  learningObjectives: [
    "Map a constraint to a component instead of expecting the model to cover it.",
    "Stay inside a relative cost and latency budget while covering the required concerns.",
    "Avoid stacking two blocks that the scenario marks as conflicting.",
    "Include an observability block when the operator has to explain a later failure.",
  ],
  concepts: ["Model routing", "Retrieval", "Guardrails", "Verification", "Caching", "Tool use", "Observability"],
  bloomLevels: ["analyze", "evaluate"],
  prerequisites: [],
  estimatedMinutes: 25,
  difficulty: "advanced",
  masteryThreshold: 70,
  misconception: "Adding a larger model is not a substitute for retrieval, a guardrail, or a log.",
  reflectionPrompt: "Which block in your composition would you remove first if the latency budget were cut in half, and what constraint would you then fail?",
  workedExample: {
    title: "A grounded FAQ",
    steps: [
      "List the concerns the scenario names: grounding, safety, latency, operations.",
      "Pick one block that covers each. A block may cover more than one.",
      "Add the relative costs. If you are over budget, remove a block that duplicates a concern.",
      "Do not select two blocks whose conflict list names each other.",
    ],
  },
  furtherReadingIds: ["lewis2020rag", "huyen2022dmls", "ouyang2022instructgpt"],
  implementation: {
    type: "deterministic-simulation",
    label: "Architecture assembly with relative units",
    whatIsReal: "Sums of authored cost and latency, plus set coverage of the named concerns.",
    whatIsSimulated: "No services are deployed. Cost and latency units are teaching numbers, not a cloud quote.",
  },
  rounds: [
    {
      id: "faq",
      title: "Round 1 · A policy FAQ",
      concept: "Grounding and a guardrail",
      learnerTask: "Cover grounding and safety inside cost 6 and latency 40.",
      expectedReasoning: "Retrieval covers grounding. A guardrail covers safety. The giant model is expensive and covers neither by itself.",
      scenario: "A student handbook bot must quote the handbook and refuse requests to change grades. Relative budgets: cost 6, latency 40.",
      hints: [
        "The base model does not cover grounding or safety in this table.",
        "You need retrieval and a guardrail.",
        "Those two blocks together cost 5 and add latency 30. Leave the giant model off.",
      ],
      scoringRule: scoreRule,
      explanation: "The model generates. Retrieval decides what it is allowed to rely on. The guardrail decides what it must not do. They are different blocks.",
      feedbackCorrect: "Grounding and safety are both assigned to a block, inside the budget.",
      feedbackIncorrect: "The giant model does not cover the two required concerns. Add the blocks that do.",
      interaction: {
        type: "composer",
        prompt: "Assemble the FAQ bot.",
        maxCost: 6,
        maxLatency: 40,
        requiredCovers: ["grounding", "safety"],
        blocks: [
          { id: "model", label: "Base model", description: "Generates the reply.", covers: [], cost: 2, latency: 15, conflicts: [] },
          { id: "giant", label: "Giant model", description: "More fluent, still ungrounded.", covers: [], cost: 6, latency: 30, conflicts: [] },
          { id: "rag", label: "Handbook retrieval", description: "Retrieves policy chunks.", covers: ["grounding"], cost: 2, latency: 12, conflicts: [] },
          { id: "guard", label: "Grade-change guardrail", description: "Refuses grade-change requests.", covers: ["safety"], cost: 1, latency: 4, conflicts: [] },
        ],
      },
    },
    {
      id: "cache",
      title: "Round 2 · Repeated questions",
      concept: "Caching",
      learnerTask: "Cover grounding and latency. The latency budget is too tight for retrieval on every call unless a cache is present.",
      expectedReasoning: "Retrieval alone exceeds latency. Cache covers latency. Together they fit.",
      scenario: "Eighty percent of questions are repeats of the add/drop rule. p95 budget is a relative latency of 20. Cost budget is 8.",
      hints: [
        "Read the latency of retrieval by itself.",
        "The cache is what covers the latency concern.",
        "Select retrieval and cache. Skip the uncached giant path.",
      ],
      scoringRule: scoreRule,
      explanation: "A cache is part of the architecture when the workload repeats. It does not ground a new question; retrieval still has to exist for the misses.",
      feedbackCorrect: "Repeats can be fast and new questions can still be grounded.",
      feedbackIncorrect: "Retrieval without the cache misses the latency budget in this table.",
      interaction: {
        type: "composer",
        prompt: "Assemble the add/drop bot.",
        maxCost: 8,
        maxLatency: 20,
        requiredCovers: ["grounding", "latency"],
        blocks: [
          { id: "rag", label: "Policy retrieval", description: "Grounds add/drop answers.", covers: ["grounding"], cost: 2, latency: 18, conflicts: [] },
          { id: "cache", label: "Reply cache", description: "Serves repeated questions.", covers: ["latency"], cost: 1, latency: 1, conflicts: [] },
          { id: "giant", label: "Giant model, no cache", description: "Slow and ungrounded.", covers: [], cost: 5, latency: 28, conflicts: ["cache"] },
        ],
      },
    },
    {
      id: "tools",
      title: "Round 3 · A tool with a check",
      concept: "Tool use and verification",
      learnerTask: "Cover tools and verification. Do not select the tool block together with the block it conflicts with.",
      expectedReasoning: "The registrar tool covers the tool concern. The confirmation step covers verification. The auto-submit block conflicts with confirmation.",
      scenario: "The bot may look up a student's own enrollment and must show it before answering. It must not submit a form. Cost budget 7, latency 30.",
      hints: [
        "Auto-submit conflicts with confirmation.",
        "You need the lookup tool and the confirmation step.",
        "Leave auto-submit off. Cost of lookup plus confirmation is 4.",
      ],
      scoringRule: scoreRule,
      explanation: "Tool use without a check is how a system takes an action nobody reviewed. The conflict edge is the scenario's way of saying those two policies cannot both be active.",
      feedbackCorrect: "The lookup exists and a person sees the result before it is trusted.",
      feedbackIncorrect: "Auto-submit conflicts with the confirmation block. Remove it.",
      interaction: {
        type: "composer",
        prompt: "Assemble the enrollment lookup.",
        maxCost: 7,
        maxLatency: 30,
        requiredCovers: ["tools", "verification"],
        blocks: [
          { id: "lookup", label: "Enrollment lookup", description: "Read-only tool.", covers: ["tools"], cost: 2, latency: 8, conflicts: [] },
          { id: "confirm", label: "Show the record first", description: "Verification before the reply is final.", covers: ["verification"], cost: 1, latency: 3, conflicts: ["autosubmit"] },
          { id: "autosubmit", label: "Auto-submit a change", description: "Writes a form.", covers: [], cost: 2, latency: 6, conflicts: ["confirm"] },
        ],
      },
    },
    {
      id: "router",
      title: "Round 4 · Route the easy calls",
      concept: "Model routing",
      learnerTask: "Cover routing, grounding, and cost. A single giant model for every call breaks the cost budget.",
      expectedReasoning: "The router sends easy calls to a small model and hard calls to retrieval plus a larger model. That is the cost cover. Retrieval is still required for grounding.",
      scenario: "Half of the traffic is “what are office hours?” The cost budget is 7. Ungrounded answers are not acceptable, and the office still wants a routing story for the easy half.",
      hints: [
        "The giant-for-everything block is over budget once retrieval is added, and it does not cover routing.",
        "The router block is what covers cost in this table.",
        "Select router and retrieval.",
      ],
      scoringRule: scoreRule,
      explanation: "Routing is an architecture choice about which model sees which call. It is not a prompt trick.",
      feedbackCorrect: "Easy calls have a route, and policy calls still have retrieval.",
      feedbackIncorrect: "Add the router. The giant-only path does not cover routing and spends the budget.",
      interaction: {
        type: "composer",
        prompt: "Assemble the routed assistant.",
        maxCost: 7,
        maxLatency: 35,
        requiredCovers: ["routing", "grounding", "cost"],
        blocks: [
          { id: "router", label: "Model router", description: "Easy calls go to a small model.", covers: ["routing", "cost"], cost: 2, latency: 4, conflicts: ["giant"] },
          { id: "rag", label: "Hours and policy retrieval", description: "Grounds policy answers.", covers: ["grounding"], cost: 2, latency: 10, conflicts: [] },
          { id: "giant", label: "Giant model for every call", description: "No router.", covers: [], cost: 6, latency: 20, conflicts: ["router"] },
        ],
      },
    },
    {
      id: "observe",
      title: "Round 5 · Someone has to explain Tuesday",
      concept: "Observability",
      learnerTask: "Cover grounding, safety, and observability inside the budget.",
      expectedReasoning: "A trace log is the observability block. Without it the other blocks can be correct and still undebuggable.",
      scenario: "After a bad answer last Tuesday, nobody could say which chunk was retrieved. The next design must log the route, the chunk ids, and the guardrail decision. Cost budget 8, latency 40.",
      hints: [
        "Observability is a required concern, not a nice-to-have in this round.",
        "The trace block is cheap.",
        "Select retrieval, guardrail, and traces.",
      ],
      scoringRule: scoreRule,
      explanation: "Observability is how the other components remain teachable and operable. A system that cannot name its chunk is not yet grounded in a way an instructor can audit.",
      feedbackCorrect: "The design can answer, refuse, and explain which chunk it used.",
      feedbackIncorrect: "The trace block is what covers observability. The other two do not.",
      interaction: {
        type: "composer",
        prompt: "Assemble an auditable assistant.",
        maxCost: 8,
        maxLatency: 40,
        requiredCovers: ["grounding", "safety", "observability"],
        blocks: [
          { id: "rag", label: "Retrieval", description: "Returns chunk ids.", covers: ["grounding"], cost: 2, latency: 12, conflicts: [] },
          { id: "guard", label: "Guardrail", description: "Records allow or refuse.", covers: ["safety"], cost: 1, latency: 4, conflicts: [] },
          { id: "trace", label: "Trace log", description: "Stores route, chunk ids, and the guardrail decision.", covers: ["observability"], cost: 1, latency: 2, conflicts: [] },
          { id: "giant", label: "Giant model only", description: "No log and no retrieval.", covers: [], cost: 6, latency: 25, conflicts: [] },
        ],
      },
    },
  ],
};

export default systemComposer;
