import { tokenForgeOrientation } from "../orientation/games.ts";
import { tokenForgeTeaching } from "../teaching/forge.ts";
import type { GameDefinition } from "../../src/game-engine/schema.ts";

const scoreRule =
  "The precomputed segmentation marked best scores 10 points. An acceptable segmentation scores 6. A poor fit scores 0. Each revealed hint then subtracts 1 point, to a floor of 0. Token counts and costs are calculated from the authored segments; they are not a live tokenizer.";

const tokenForge: GameDefinition = {
  id: "token-forge",
  status: "implemented",
  title: "Token Forge",
  tier: 1,
  order: 1,
  summary:
    "See how text becomes the discrete units processed by a language model. Compare subword segmentation strategies and reason about vocabulary, sequence length, multilingual text, code, context use, and token-related cost.",
  purpose: "Make tokenization visible so learners can connect segmentation choices to sequence length and API cost.",
  whyItMatters:
    "Model APIs bill and attend over tokens, not characters. A segmentation that looks similar on the page can change cost, context fit, and how rare words are represented.",
  learningObjectives: [
    "Compare BPE, WordPiece, SentencePiece, and Unigram segmentations of the same string.",
    "Compute a token count from a displayed segmentation.",
    "Estimate call cost from a token count and a published per-million-token price.",
    "Explain one case where a morphologically rich word or mixed-script string changes the preferred segmentation.",
  ],
  concepts: ["Tokens", "BPE", "WordPiece", "SentencePiece", "Unigram", "Token cost"],
  bloomLevels: ["remember", "understand", "apply"],
  prerequisites: [],
  estimatedMinutes: 20,
  difficulty: "foundational",
  masteryThreshold: 70,
  misconception: "A token is not the same thing as a word, and a shorter character string is not automatically cheaper.",
  reflectionPrompt: "Describe one production text type where you would inspect tokenization before choosing a model, and what you would measure.",
  workedExample: {
    title: "Counting a precomputed segmentation",
    steps: [
      "Read the string exactly as the caller would send it.",
      "Look at each candidate's pieces. The piece count is the token count in this exercise.",
      "Multiply tokens by the price per million tokens and by the number of calls.",
      "Prefer the segmentation the round marks as best only after you can say which linguistic feature it handled.",
    ],
  },
  furtherReadingIds: ["sennrich2016", "schuster2012", "kudo2018sentencepiece", "kudo2018unigram"],
  implementation: {
    type: "precomputed",
    label: "Precomputed educational segmentations",
    whatIsReal: "Token counts, efficiency figures, and dollar estimates are arithmetic on the segments shown.",
    whatIsSimulated:
      "The segments are authored illustrations of how these families often behave. They are not the output of a production tokenizer library.",
  },
  orientation: tokenForgeOrientation,
  teaching: tokenForgeTeaching,
  rounds: [
    {
      id: "english-clause",
      title: "Round 1 · A plain English sentence",
      concept: "Word-like pieces versus subwords",
      learnerTask: "Choose the segmentation with the best cost-quality fit for a frequent English sentence.",
      expectedReasoning: "Frequent English words can stay intact. A family that slices them into characters spends tokens the sentence does not need.",
      scenario: "This is the sentence the original classroom exercise used for ordinary English: “The quick brown fox jumps over the lazy dog.”",
      hints: [
        "Start by counting pieces, not characters.",
        "For frequent English, prefer the row that keeps whole words.",
        "In this authored comparison the BPE row is the shortest and is marked best.",
      ],
      scoringRule: scoreRule,
      explanation:
        "The classroom prototype taught this sentence as a BPE case. These pieces are still authored illustrations, not the output of a BPE merge. A real BPE vocabulary can segment this sentence differently.",
      feedbackCorrect: "The BPE row keeps the frequent English words intact in this authored comparison.",
      feedbackIncorrect: "Count the pieces. The shortest row that still shows every word is the one marked best.",
      interaction: {
        type: "tokenizer",
        text: "The quick brown fox jumps over the lazy dog",
        objective: "Minimize tokens for a frequent English sentence without discarding words.",
        pricePerMillionTokensUsd: 5,
        calls: 1000000,
        strategies: [
          {
            id: "bpe",
            name: "BPE",
            summary: "Nine authored pieces. Frequent English words stay whole.",
            tokens: ["The", " quick", " brown", " fox", " jumps", " over", " the", " lazy", " dog"],
            vocabEfficiency: 90,
            quality: "best",
          },
          {
            id: "wordpiece",
            name: "WordPiece",
            summary: "Ten authored pieces. The verb is split with a continuation marker.",
            tokens: ["The", "quick", "brown", "fox", "jump", "##s", "over", "the", "lazy", "dog"],
            vocabEfficiency: 82,
            quality: "acceptable",
          },
          {
            id: "sentencepiece",
            name: "SentencePiece",
            summary: "Ten authored pieces. Whitespace markers stay visible and the verb is split.",
            tokens: ["▁The", "▁quick", "▁brown", "▁fox", "▁jump", "s", "▁over", "▁the", "▁lazy", "▁dog"],
            vocabEfficiency: 80,
            quality: "acceptable",
          },
          {
            id: "unigram",
            name: "Unigram",
            summary: "Twelve authored pieces. This row over-splits fox and jumps to show a costly segmentation.",
            tokens: ["▁The", "▁quick", "▁brown", "▁f", "ox", "▁j", "u", "mps", "▁over", "▁the", "▁lazy", "▁dog"],
            vocabEfficiency: 64,
            quality: "poor",
          },
        ],
      },
    },
    {
      id: "python-signature",
      title: "Round 2 · A Python signature",
      concept: "Code punctuation and snake case",
      learnerTask: "Choose the segmentation that best preserves code structure at a lower token count.",
      expectedReasoning: "Punctuation and snake_case create many merges. A family that keeps identifiers together is cheaper here.",
      scenario: "An internal tool sends function signatures as part of a code-review prompt. Identifier splits make the prompt longer and harder to align with the AST.",
      hints: [
        "Count underscores, brackets, and colons as carefully as words.",
        "Prefer the row that keeps refund_total together.",
        "SentencePiece is marked best here because the authored pieces keep the identifier and the list annotation compact.",
      ],
      scoringRule: scoreRule,
      explanation:
        "Code is a different distribution from prose. This comparison was written so SentencePiece keeps the identifier intact. That is a teaching choice, not a benchmark of the SentencePiece library.",
      feedbackCorrect: "Keeping the identifier intact reduced the authored token count for this signature.",
      feedbackIncorrect: "Look for the segmentation that does not slice refund_total into many pieces.",
      interaction: {
        type: "tokenizer",
        text: "def refund_total(items: list[str]) -> int:",
        objective: "Minimize tokens while keeping the function name recognizable.",
        pricePerMillionTokensUsd: 15,
        calls: 250000,
        strategies: [
          {
            id: "bpe",
            name: "BPE",
            summary: "Pairs have not fully merged the snake-case name in this row.",
            tokens: ["def", " ref", "und", "_", "total", "(", "items", ":", " list", "[", "str", "])", " ->", " int", ":"],
            vocabEfficiency: 61,
            quality: "poor",
          },
          {
            id: "wordpiece",
            name: "WordPiece",
            summary: "Continuation marks appear inside the name and the brackets.",
            tokens: ["def", "refund", "_", "total", "(", "items", ":", "list", "[", "str", "]", ")", "-", ">", "int", ":"],
            vocabEfficiency: 64,
            quality: "poor",
          },
          {
            id: "sentencepiece",
            name: "SentencePiece",
            summary: "The identifier and the annotation stay in fewer authored pieces.",
            tokens: ["▁def", "▁refund_total", "(", "items", ":", "▁list", "[str]", ")", "▁->", "▁int:"],
            vocabEfficiency: 86,
            quality: "best",
          },
          {
            id: "unigram",
            name: "Unigram",
            summary: "Closer than BPE, but the arrow and brackets are still separate pieces.",
            tokens: ["▁def", "▁refund", "_", "total", "(", "items:", "▁list[str]", ")", "▁->", "▁int", ":"],
            vocabEfficiency: 79,
            quality: "acceptable",
          },
        ],
      },
    },
    {
      id: "german-compound",
      title: "Round 3 · A long compound",
      concept: "Morphologically rich words",
      learnerTask: "Choose the segmentation that handles a long German compound most efficiently.",
      expectedReasoning: "Character or naive word splits are wasteful. Subword families that know common morphemes use fewer pieces.",
      scenario: "A bilingual logistics bot quotes German legal names. One compound can dominate the token budget if it shatters into characters.",
      hints: [
        "This word is one orthographic word and many morphemes.",
        "The poor row is the one that falls back toward single characters.",
        "The best row in this exercise splits the compound into a handful of meaningful pieces, not one opaque blob and not thirty letters.",
      ],
      scoringRule: scoreRule,
      explanation:
        "Subword models exist partly so rare compounds can be built from frequent parts. The counts here are authored to make that tradeoff visible.",
      feedbackCorrect: "A handful of subword pieces is the efficient authored segmentation for this compound.",
      feedbackIncorrect: "Avoid both the character-level shatter and the single opaque token that cannot be reused.",
      interaction: {
        type: "tokenizer",
        text: "Donaudampfschifffahrtsgesellschaft",
        objective: "Represent the compound with reusable subword pieces.",
        pricePerMillionTokensUsd: 5,
        calls: 1000000,
        strategies: [
          {
            id: "bpe",
            name: "BPE",
            summary: "Several frequent German pieces, plus a leftover fragment.",
            tokens: ["Donau", "dampf", "schiff", "fahrt", "s", "gesellschaft"],
            vocabEfficiency: 84,
            quality: "acceptable",
          },
          {
            id: "wordpiece",
            name: "WordPiece",
            summary: "Many continuation pieces, close to a character fallback.",
            tokens: ["D", "##ona", "##ud", "##amp", "##fs", "##chi", "##ff", "##ahrt", "##sge", "##sell", "##schaft"],
            vocabEfficiency: 48,
            quality: "poor",
          },
          {
            id: "sentencepiece",
            name: "SentencePiece",
            summary: "Four authored morpheme-like pieces.",
            tokens: ["▁Donau", "dampfschiff", "fahrts", "gesellschaft"],
            vocabEfficiency: 91,
            quality: "best",
          },
          {
            id: "unigram",
            name: "Unigram",
            summary: "A plausible alternative segmentation with one extra piece.",
            tokens: ["▁Donau", "dampf", "schifffahrt", "s", "gesellschaft"],
            vocabEfficiency: 87,
            quality: "acceptable",
          },
        ],
      },
    },
    {
      id: "mixed-script",
      title: "Round 4 · Mixed script",
      concept: "Multilingual tokenization",
      learnerTask: "Choose the segmentation that stays compact across Latin and Japanese text.",
      expectedReasoning: "A vocabulary built for English can split an unfamiliar script into many bytes or unknown pieces.",
      scenario: "An invoice assistant must copy a company name in Japanese inside an English sentence. The name should not explode the context budget.",
      hints: [
        "Find the script that is not Latin.",
        "The poor rows isolate that name into many single-character pieces.",
        "SentencePiece is marked best because this authored row keeps the company name in two pieces.",
      ],
      scoringRule: scoreRule,
      explanation:
        "Multilingual tokenizers are often trained with byte fallback or language-agnostic pieces so unknown scripts do not become one token per character. These rows illustrate that idea.",
      feedbackCorrect: "The compact treatment of the Japanese name is the better authored fit.",
      feedbackIncorrect: "Look at the company name, not the English words. One row shatters it.",
      interaction: {
        type: "tokenizer",
        text: "Please send the factura to 株式会社 Example by Friday.",
        objective: "Keep the mixed-script name compact.",
        pricePerMillionTokensUsd: 8,
        calls: 500000,
        strategies: [
          {
            id: "bpe",
            name: "BPE",
            summary: "English stays compact. The company name is several byte-like pieces.",
            tokens: ["Please", " send", " the", " factura", " to", " 株", "式", "会社", " Example", " by", " Friday", "."],
            vocabEfficiency: 70,
            quality: "acceptable",
          },
          {
            id: "wordpiece",
            name: "WordPiece",
            summary: "Unknown-character fallback on every kanji.",
            tokens: ["Please", "send", "the", "factura", "to", "株", "式", "会", "社", "Example", "by", "Friday", "."],
            vocabEfficiency: 55,
            quality: "poor",
          },
          {
            id: "sentencepiece",
            name: "SentencePiece",
            summary: "The company name is two pieces in this authored row.",
            tokens: ["▁Please", "▁send", "▁the", "▁factura", "▁to", "▁株式会社", "▁Example", "▁by", "▁Friday", "."],
            vocabEfficiency: 90,
            quality: "best",
          },
          {
            id: "unigram",
            name: "Unigram",
            summary: "Better than the character fallback, still one extra piece on the name.",
            tokens: ["▁Please", "▁send", "▁the", "▁factura", "▁to", "▁株式", "会社", "▁Example", "▁by", "▁Friday."],
            vocabEfficiency: 82,
            quality: "acceptable",
          },
        ],
      },
    },
    {
      id: "legal-cost",
      title: "Round 5 · A clause at volume",
      concept: "Token cost at production volume",
      learnerTask: "Choose the segmentation that reduces cost on one million calls without dropping the operative phrase.",
      expectedReasoning: "A 17 percent token reduction is a real invoice change at this volume, even though the text looks similar.",
      scenario:
        "Your inference API replays a limitation-of-liability clause on every request. Finance asked for a cheaper prompt that still contains the operative phrase.",
      hints: [
        "Compute cost as tokens × price per million × calls, with calls already set to one million.",
        "The operative phrase is “liability is limited.” Do not pick a row that deletes it; none of these rows delete it.",
        "SentencePiece has 19 authored tokens and WordPiece has 23. Count the pieces on the card rather than trusting a summary.",
      ],
      scoringRule: scoreRule,
      explanation:
        "At one million calls, token count is the cost driver in this exercise. The 19-versus-23 comparison is authored so the arithmetic is easy to check. It is the same style of feedback described for Token Forge in the Odyssey paper, using precomputed segments.",
      feedbackCorrect: "SentencePiece's 19 authored tokens beat WordPiece's 23 on this clause, which is about a 17 percent reduction.",
      feedbackIncorrect: "Put the two lowest counts side by side. The best row is the shorter one that still shows every operative word.",
      interaction: {
        type: "tokenizer",
        text: "The contractor's aggregate liability under this schedule is limited to fees paid in the prior three months.",
        objective: "Minimize cost per million calls.",
        pricePerMillionTokensUsd: 10,
        calls: 1000000,
        strategies: [
          {
            id: "bpe",
            name: "BPE",
            summary: "A middle count with the possessive still split.",
            tokens: ["The", " contract", "or", "'s", " aggregate", " liability", " under", " this", " schedule", " is", " limited", " to", " fees", " paid", " in", " the", " prior", " three", " months", "."],
            vocabEfficiency: 73,
            quality: "acceptable",
          },
          {
            id: "wordpiece",
            name: "WordPiece",
            summary: "23 authored pieces. The possessive and liability are split into continuation pieces.",
            tokens: ["The", "contract", "##or", "'", "s", "aggregate", "li", "##ability", "under", "this", "schedule", "is", "limited", "to", "fees", "paid", "in", "the", "prior", "three", "month", "##s", "."],
            vocabEfficiency: 69,
            quality: "poor",
          },
          {
            id: "sentencepiece",
            name: "SentencePiece",
            summary: "19 authored pieces, including the operative limitation language. The possessive stays with the noun.",
            tokens: ["▁The", "▁contractor", "'s", "▁aggregate", "▁liability", "▁under", "▁this", "▁schedule", "▁is", "▁limited", "▁to", "▁fees", "▁paid", "▁in", "▁the", "▁prior", "▁three", "▁months", "."],
            vocabEfficiency: 92,
            quality: "best",
          },
          {
            id: "unigram",
            name: "Unigram",
            summary: "20 authored pieces. The possessive is split, so the count is one higher than SentencePiece.",
            tokens: ["▁The", "▁contractor", "'", "s", "▁aggregate", "▁liability", "▁under", "▁this", "▁schedule", "▁is", "▁limited", "▁to", "▁fees", "▁paid", "▁in", "▁the", "▁prior", "▁three", "▁months", "."],
            vocabEfficiency: 86,
            quality: "acceptable",
          },
        ],
      },
    },
  ],
};

export default tokenForge;
